window.PRAETERITUM_TEXT_LIBRARY = (function () {
  var INTRO = "Verwandle alle Saetze in das Praeteritum und achte auf die passenden Verbformen.";
  var CLIPARTS = {
    school: ["??", "??", "??", "??"],
    garden: ["??", "??", "??", "??"],
    playground: ["??", "?", "??", "??"],
    family: ["??", "??", "??", "??"],
    reading: ["??", "??", "???", "??"],
    swim: ["??", "??", "??", "??"],
    zoo: ["??", "??", "??", "???"],
    birthday: ["??", "??", "??", "??"],
    music: ["??", "??", "??", "??"],
    camp: ["?", "??", "??", "??"]
  };

  function tokens(sentence) {
    return sentence.match(/[A-Za-zƒ÷‹‰ˆ¸ﬂ]+(?:-[A-Za-zƒ÷‹‰ˆ¸ﬂ]+)*|[0-9]+|[,.;:!?]/g) || [];
  }

  function makeText(title, topic, theme, pairs) {
    var sentences = [];
    var i;
    for (i = 0; i < pairs.length; i += 1) {
      sentences.push({ present: tokens(pairs[i][0]), past: tokens(pairs[i][1]) });
    }
    return {
      title: title,
      topic: topic,
      theme: theme,
      cliparts: CLIPARTS[theme].slice(),
      intro: INTRO,
      sentences: sentences
    };
  }

  function story(spec) {
    return makeText(spec.title, spec.topic, spec.theme, [
      ["Heute arbeitet " + spec.name + " an einem neuen Thema.", "Heute arbeitete " + spec.name + " an einem neuen Thema."],
      [spec.name + " sieht zuerst " + spec.focus + ".", spec.name + " sah zuerst " + spec.focus + "."],
      [spec.name + " nimmt " + spec.item + " in die Hand und beginnt ruhig.", spec.name + " nahm " + spec.item + " in die Hand und begann ruhig."],
      [spec.friend + " kommt dazu, tr‰gt " + spec.tool + " herbei und hilft gleich mit.", spec.friend + " kam dazu, trug " + spec.tool + " herbei und half gleich mit."],
      ["Dann entdeckt " + spec.name + " " + spec.highlight + " und zeigt sofort darauf.", "Dann entdeckte " + spec.name + " " + spec.highlight + " und zeigte sofort darauf."],
      ["Gemeinsam schreiben, bauen oder ordnen beide alles weiter.", "Gemeinsam schrieben, bauten oder ordneten beide alles weiter."],
      [spec.friend + " findet sp‰ter " + spec.extra + " und gibt es " + spec.name + ".", spec.friend + " fand sp‰ter " + spec.extra + " und gab es " + spec.name + "."],
      ["Am Ende pr¸ft " + spec.name + " alles noch einmal genau und spricht ¸ber " + spec.topicWord + ".", "Am Ende pr¸fte " + spec.name + " alles noch einmal genau und sprach ¸ber " + spec.topicWord + "."]
    ]);
  }

  var specs = [
    { title: "Fruehdienst im Klassenraum", topic: "Schule", theme: "school", name: "Jana", friend: "Emil", place: "den Klassenraum", focus: "den Wochenplan", item: "eine Kiste mit Kreide", tool: "den Tafelschwamm", highlight: "eine neue Liste an der Tafel", extra: "einen roten Stift", topicWord: "den Tafeldienst" },
    { title: "Das neue Matheheft", topic: "Schule", theme: "school", name: "Mila", friend: "Tom", place: "das Klassenzimmer", focus: "die dritte Aufgabe", item: "ihr neues Matheheft", tool: "den Radiergummi", highlight: "eine schwierige Zahl", extra: "eine fehlende Rechnung", topicWord: "den Rechenweg" },
    { title: "Referat ueber Sterne", topic: "Schule", theme: "school", name: "Noah", friend: "Kira", place: "den Sachkunderaum", focus: "das Plakat mit dem Mond", item: "einen Laserpointer", tool: "das Sternenheft", highlight: "eine Rakete auf dem Bild", extra: "eine Planetenkarte", topicWord: "das Sonnensystem" },
    { title: "Regenpause im Flur", topic: "Schule", theme: "school", name: "Leni", friend: "Yusuf", place: "den langen Flur", focus: "den Kartenturm", item: "ein Kartenspiel", tool: "den Wuerfelbecher", highlight: "einen schiefen Stapel", extra: "eine fehlende Karte", topicWord: "die Regenpause" },
    { title: "Kunst mit Wasserfarben", topic: "Schule", theme: "school", name: "Sara", friend: "Paul", place: "den Kunstraum", focus: "den blauen Himmel", item: "ihren Wasserfarbkasten", tool: "den duennen Pinsel", highlight: "einen mutigen Farbwechsel", extra: "einen sauberen Schwamm", topicWord: "die Farbideen" },
    { title: "Sporttag auf dem Hof", topic: "Schule", theme: "school", name: "Nils", friend: "Lea", place: "den Schulhof", focus: "die Ziellinie", item: "seine Sportschuhe", tool: "die Startfahne", highlight: "eine freie Laufbahn", extra: "eine Urkunde", topicWord: "den Staffellauf" },
    { title: "Partnerarbeit in Sachkunde", topic: "Schule", theme: "school", name: "Mara", friend: "Jonas", place: "den Forschertisch", focus: "die Steinekiste", item: "eine Lupe", tool: "das Notizblatt", highlight: "einen glatten Kiesel", extra: "einen schweren Brocken", topicWord: "die Gesteine" },
    { title: "Ausflug zur Baeckerei", topic: "Schule", theme: "school", name: "Fina", friend: "Theo", place: "die Baeckerei", focus: "die grossen Brezeln", item: "eine Probiertuete", tool: "den Teigschieber", highlight: "ein warmes Blech", extra: "ein Sesambrot", topicWord: "das Backen" },
    { title: "Der Klassenrat am Freitag", topic: "Schule", theme: "school", name: "Ava", friend: "Ben", place: "den Sitzkreis", focus: "den Rede-Stein", item: "das Protokollblatt", tool: "einen Bleistift", highlight: "einen neuen Vorschlag", extra: "einen zweiten Wunsch", topicWord: "die Klassenregeln" },
    { title: "Ein Brief an die Parallelklasse", topic: "Schule", theme: "school", name: "Leonie", friend: "Oskar", place: "den Deutschraum", focus: "den Briefumschlag", item: "den Fuelleder", tool: "das Woerterbuch", highlight: "eine freundliche Anrede", extra: "ein Komma", topicWord: "die Antwort" },
    { title: "Das Beet hinter der Turnhalle", topic: "Natur", theme: "garden", name: "Jule", friend: "Finn", place: "das Beet hinter der Turnhalle", focus: "die jungen Blumen", item: "kleine Steine", tool: "eine gruene Giesskanne", highlight: "einen Marienkaefer", extra: "einen Regenwurm", topicWord: "die neuen Pflanzen" },
    { title: "Tag auf dem Abenteuerspielplatz", topic: "Freizeit", theme: "playground", name: "Sami", friend: "Pia", place: "den Abenteuerspielplatz", focus: "das Holzschiff", item: "einen Schatzplan", tool: "ein starkes Tau", highlight: "eine alte Dose", extra: "einen Murmelbeutel", topicWord: "das Piratenspiel" },
    { title: "Die Erbsen im Hochbeet", topic: "Natur", theme: "garden", name: "Tara", friend: "Mats", place: "das Hochbeet", focus: "die dicken Schoten", item: "das Gartenheft", tool: "eine kleine Lupe", highlight: "eine geoeffnete Schote", extra: "feine Blattadern", topicWord: "die Ernte" },
    { title: "Seilspringen auf dem Hof", topic: "Freizeit", theme: "playground", name: "Lias", friend: "Mina", place: "den Hof", focus: "die Sprungzahl", item: "ein langes Seil", tool: "eine Kreidetafel", highlight: "einen neuen Rekord", extra: "einen sicheren Rhythmus", topicWord: "das Seilspringen" },
    { title: "Blumen fuer den Klassenraum", topic: "Natur", theme: "garden", name: "Ella", friend: "Jonte", place: "das Hofbeet", focus: "den bunten Strauss", item: "abgeschnittene Stiele", tool: "eine Glasvase", highlight: "eine kleine Schnecke", extra: "lange Blaetter", topicWord: "die Blumen" },
    { title: "Der Drachen im Herbstwind", topic: "Freizeit", theme: "playground", name: "Benni", friend: "Romy", place: "die Wiese am Feld", focus: "den langen Schweif", item: "die Schnurrolle", tool: "den Drachenstab", highlight: "einen starken Wind", extra: "einen festen Knoten", topicWord: "den Flug" },
    { title: "Der Regenmesser im Garten", topic: "Natur", theme: "garden", name: "Yara", friend: "Leo", place: "den Gartenweg", focus: "den Regenmesser", item: "ein Lineal", tool: "das Wetterheft", highlight: "die hohe Messzahl", extra: "schwimmende Blaetter", topicWord: "den Regen" },
    { title: "Roller auf der Schulstrasse", topic: "Freizeit", theme: "playground", name: "Ole", friend: "Henri", place: "die ruhige Schulstrasse", focus: "den Parcours", item: "den Roller", tool: "kleine Huetchen", highlight: "eine scharfe Kurve", extra: "eine sichere Spur", topicWord: "die Proberunde" },
    { title: "Das Insektenhotel", topic: "Natur", theme: "garden", name: "Luca", friend: "Mia", place: "den Schulgarten", focus: "das Holzhaus", item: "Zapfen und Schilf", tool: "die Schraubenkiste", highlight: "eine Biene am Zaun", extra: "eine lose Schraube", topicWord: "die Insekten" },
    { title: "Fussball am Nachmittag", topic: "Freizeit", theme: "playground", name: "Noor", friend: "Malik", place: "den Bolzplatz", focus: "das linke Tor", item: "den Ball", tool: "weisse Kreide", highlight: "einen schnellen Pass", extra: "einen Schuss in die Ecke", topicWord: "das Spiel" },
    { title: "Apfelsaft fuer Oma", topic: "Familie", theme: "family", name: "Leni", friend: "Oma", place: "die Kueche", focus: "den warmen Duft", item: "frische Aepfel", tool: "den grossen Topf", highlight: "den ersten Saft", extra: "ein Etikett", topicWord: "das Rezept" },
    { title: "Der Hund auf dem Sofa", topic: "Familie", theme: "family", name: "Tabea", friend: "Jonas", place: "das Wohnzimmer", focus: "Bello auf dem Sofa", item: "ein Leckerli", tool: "den Wassernapf", highlight: "die wedelnde Rute", extra: "ein trockenes Kissen", topicWord: "den Hund" },
    { title: "Ein Streit um das Bausteinhaus", topic: "Familie", theme: "family", name: "Ida", friend: "Moritz", place: "das Kinderzimmer", focus: "den umgekippten Turm", item: "ein Fensterstein", tool: "die grosse Grundplatte", highlight: "ein rotes Dachteil", extra: "eine neue Idee", topicWord: "die Versoehnung" },
    { title: "Pancakes am Sonntag", topic: "Familie", theme: "family", name: "Elias", friend: "Mama", place: "die Kueche", focus: "den ersten Pancake", item: "die Schuessel mit Teig", tool: "den Schneebesen", highlight: "den Sirup", extra: "eine Banane", topicWord: "das Fruehstueck" },
    { title: "Die verschwundene Socke", topic: "Familie", theme: "family", name: "Paula", friend: "Papa", place: "das Schlafzimmer", focus: "den Kleiderhaufen", item: "eine blaue Socke", tool: "die obere Schublade", highlight: "eine alte Jacke", extra: "den fehlenden Zwilling", topicWord: "die Suche" },
    { title: "Besuch beim Opa", topic: "Familie", theme: "family", name: "Mira", friend: "Opa", place: "den Garten", focus: "die Werkzeugkiste", item: "eine Holzleiste", tool: "das Schleifpapier", highlight: "einen alten Hobel", extra: "ein Brett", topicWord: "das Holz" },
    { title: "Ein Abend ohne Strom", topic: "Familie", theme: "family", name: "Nico", friend: "Lea", place: "das Wohnzimmer", focus: "die flackernden Schatten", item: "eine Taschenlampe", tool: "das Kartenspiel", highlight: "eine Kerze", extra: "einen guten Zug", topicWord: "den Stromausfall" },
    { title: "Das Regal fuer Comics", topic: "Familie", theme: "family", name: "Amelie", friend: "Onkel", place: "das Wohnzimmer", focus: "das neue Regal", item: "eine Seitenwand", tool: "die Schraubenkiste", highlight: "eine Rueckwand", extra: "eine Comicreihe", topicWord: "das Regal" },
    { title: "Der Geburtstagskalender", topic: "Familie", theme: "family", name: "Fine", friend: "Joris", place: "den Flur", focus: "den Monatsstreifen", item: "bunte Karten", tool: "den Filzstift", highlight: "Omas Datum", extra: "ein Klebeband", topicWord: "den Kalender" },
    { title: "Abendfutter fuer das Kaninchen", topic: "Familie", theme: "family", name: "Selma", friend: "Papa", place: "den Hofstall", focus: "das Kaninchen", item: "frische Moehren", tool: "die Wasserflasche", highlight: "die spitzen Ohren", extra: "frisches Stroh", topicWord: "das Futter" },
    { title: "Suche im Buechereikeller", topic: "Lesen", theme: "reading", name: "Arda", friend: "Mila", place: "der Stadtbuecherei", focus: "einen Kistentitel", item: "ein Vulkanbuch", tool: "die Regalliste", highlight: "einen roten Ruecken", extra: "eine Karteikarte", topicWord: "das Suchbuch" },
    { title: "Vorlesen in der Kuschelecke", topic: "Lesen", theme: "reading", name: "Nela", friend: "Moritz", place: "der Kuschelecke", focus: "die Fuchs-Stimme", item: "eine Tiergeschichte", tool: "das Kissen", highlight: "eine spannende Stelle", extra: "ein neues Kapitel", topicWord: "die Geschichte" },
    { title: "Der neue Buecherausweis", topic: "Lesen", theme: "reading", name: "Younes", friend: "Sara", place: "der Kinderbuecherei", focus: "die Fossilienseite", item: "ein Dinosaurierbuch", tool: "den Ausweis", highlight: "einen grossen Knochen", extra: "einen Stempelzettel", topicWord: "die Ausleihe" },
    { title: "Das geheime Regal", topic: "Lesen", theme: "reading", name: "Rina", friend: "Lea", place: "dem Klassenraum", focus: "den Umschlag mit Nummer sieben", item: "ein Ueberraschungsbuch", tool: "die Tippkiste", highlight: "eine Inselkarte", extra: "einen Tippzettel", topicWord: "das Geheimfach" },
    { title: "Lesespiel mit Taschenlampen", topic: "Lesen", theme: "reading", name: "Keno", friend: "Alina", place: "dem Schlafraum", focus: "die dunkle Ecke", item: "ein Gespensterbuch", tool: "eine Taschenlampe", highlight: "ein schwieriges Wort", extra: "eine freie Decke", topicWord: "die Lesezeit" },
    { title: "Comics tauschen", topic: "Lesen", theme: "reading", name: "Daria", friend: "Can", place: "der Pausenbank", focus: "eine lustige Zeichnung", item: "zwei Comics", tool: "einen Notizzettel", highlight: "einen starken Spruch", extra: "ein Lesezeichen", topicWord: "den Comic" },
    { title: "Das Lexikon auf dem Dachboden", topic: "Lesen", theme: "reading", name: "Mara", friend: "Onkel", place: "dem Dachboden", focus: "das Wort Wolke", item: "ein altes Lexikon", tool: "einen Zettel", highlight: "eine Zeichnung", extra: "einen Windbegriff", topicWord: "das Lexikon" },
    { title: "Eine Lesespur im Museum", topic: "Lesen", theme: "reading", name: "Jorin", friend: "Mia", place: "dem Museum", focus: "das Schlusswort", item: "eine Lesekarte", tool: "das Museumsheft", highlight: "eine goldene Uhr", extra: "die Fossilienvitrine", topicWord: "die Spur" },
    { title: "Das Buch mit der Karte", topic: "Lesen", theme: "reading", name: "Lea", friend: "Tom", place: "dem Fensterplatz", focus: "die Inselkarte", item: "ein Abenteuerbuch", tool: "einen gruuenen Stift", highlight: "einen geheimen Pfad", extra: "ein rotes Kreuz", topicWord: "die Reise" },
    { title: "Ein Gedicht fuer den Fruehling", topic: "Lesen", theme: "reading", name: "Zoe", friend: "Erik", place: "dem Deutschraum", focus: "die Windzeile", item: "ein Gedichtblatt", tool: "das Heft", highlight: "einen Reim", extra: "eine Lieblingsstrophe", topicWord: "das Gedicht" },
    { title: "Der erste Sprung vom Startblock", topic: "Sport", theme: "swim", name: "Erik", friend: "Sina", place: "das Schwimmbad", focus: "die Wende", item: "die Brille", tool: "die Stoppuhr", highlight: "die neue Zeit", extra: "einen kurzen Tipp", topicWord: "das Rennen" },
    { title: "Ein Zelt im Garten", topic: "Ferien", theme: "camp", name: "Jana", friend: "Timo", place: "das Gartenzelt", focus: "den Regenschauer", item: "die Heringe", tool: "eine Lampe", highlight: "das dichte Dach", extra: "einen Schlafsack", topicWord: "die Zeltnacht" },
    { title: "Der Badetag am Fluss", topic: "Ferien", theme: "swim", name: "Mats", friend: "Lina", place: "den Fluss", focus: "das kalte Wasser", item: "das Handtuch", tool: "die Saftflasche", highlight: "das Bojenband", extra: "einen flachen Stein", topicWord: "den Fluss" },
    { title: "Eine Nacht am Lagerfeuer", topic: "Ferien", theme: "camp", name: "Lina", friend: "Tim", place: "den Lagerplatz", focus: "die Glut", item: "einen Brotstock", tool: "einen Becher Wasser", highlight: "das Lied", extra: "eine Geschichte", topicWord: "das Feuer" },
    { title: "Das Rennen mit dem Kajak", topic: "Sport", theme: "swim", name: "Theo", friend: "Ela", place: "den Steg", focus: "die Boje", item: "das Paddel", tool: "die Startflagge", highlight: "das Ziel", extra: "einen Platzgewinn", topicWord: "das Kajak" },
    { title: "Die Spur im Wald", topic: "Ferien", theme: "camp", name: "Jette", friend: "Ben", place: "den Waldpfad", focus: "die Spur", item: "das Naturheft", tool: "die Wanderkarte", highlight: "das Reh", extra: "eine Hufzeichnung", topicWord: "den Fund" },
    { title: "Schwimmnudeln im Becken", topic: "Sport", theme: "swim", name: "Mona", friend: "Ali", place: "das Nichtschwimmerbecken", focus: "das Untertauchen", item: "die gelbe Nudel", tool: "den Beckenrand", highlight: "die neue Uebung", extra: "einen zweiten Versuch", topicWord: "das Becken" },
    { title: "Fruehstueck vor der Bergtour", topic: "Ferien", theme: "camp", name: "Emil", friend: "Rike", place: "die Waldhuette", focus: "den Anstieg", item: "den Rucksack", tool: "einen Becher Tee", highlight: "den Wanderweg", extra: "einen festen Knoten", topicWord: "die Tour" },
    { title: "Tauchen nach Ringen", topic: "Sport", theme: "swim", name: "Klara", friend: "David", place: "das tiefe Becken", focus: "den dritten Ring", item: "den roten Ring", tool: "die Stoppuhr", highlight: "den Beckenrand", extra: "den letzten Fund", topicWord: "die Tauchrunde" },
    { title: "Wuerstchen am Feuer", topic: "Ferien", theme: "camp", name: "Noe", friend: "Hedi", place: "den Feuerplatz", focus: "die Glut", item: "den Brotstock", tool: "einen Teller", highlight: "die Wurst im Brot", extra: "den Senf", topicWord: "das Abendessen" },
    { title: "Die Robbe im Morgenkreis", topic: "Zoo", theme: "zoo", name: "Mira", friend: "Ben", place: "dem Robbenbecken", focus: "die silberne Flosse", item: "einen Fischeimer", tool: "das Tierheft", highlight: "die springende Robbe", extra: "eine Frage nach Tasthaaren", topicWord: "die Robbe" },
    { title: "Pinguine auf dem Eis", topic: "Zoo", theme: "zoo", name: "Jonas", friend: "Mette", place: "dem Pinguinbecken", focus: "den watschelnden Vogel", item: "das Beobachtungsheft", tool: "das Schild", highlight: "den dicken Bauch", extra: "einen Heimatnamen", topicWord: "die Pinguine" },
    { title: "Das grosse Elefantenhaus", topic: "Zoo", theme: "zoo", name: "Amir", friend: "Lina", place: "dem Elefantenhaus", focus: "den langen Ruessel", item: "das Notizblatt", tool: "den Plan", highlight: "einen grossen Fuss", extra: "eine Sandwolke", topicWord: "den Elefanten" },
    { title: "Stille bei den Giraffen", topic: "Zoo", theme: "zoo", name: "Lea", friend: "Cem", place: "dem Giraffengehege", focus: "den langen Hals", item: "das Fernglas", tool: "das Schild", highlight: "die Fleckenzeichnung", extra: "eine Futterkiste", topicWord: "die Giraffe" },
    { title: "Eine Pause bei den Ziegen", topic: "Zoo", theme: "zoo", name: "Fabi", friend: "Fee", place: "dem Streichelzoo", focus: "die weichen Lippen", item: "den Futtereimer", tool: "die Stallkarte", highlight: "eine neugierige Ziege", extra: "eine Regelkarte", topicWord: "die Ziegen" },
    { title: "Nachts im Tropenhaus", topic: "Zoo", theme: "zoo", name: "Tom", friend: "Nina", place: "dem Tropenhaus", focus: "den kleinen Frosch", item: "das Infoblatt", tool: "das Heft", highlight: "einen grossen Fisch", extra: "eine Pflanzenwand", topicWord: "den Regenwald" },
    { title: "Der Tierpfleger im Vogelhaus", topic: "Zoo", theme: "zoo", name: "Hanna", friend: "Mila", place: "dem Vogelhaus", focus: "das rote Gefieder", item: "einen Fruchteimer", tool: "das Zeichenblatt", highlight: "ein Nest", extra: "eine Schnabelfrage", topicWord: "die Voegel" },
    { title: "Kurz vor der Loewenfuetterung", topic: "Zoo", theme: "zoo", name: "Nora", friend: "Timo", place: "dem Loewengehege", focus: "die grossen Pfoten", item: "die Eintrittskarte", tool: "das Beobachtungsblatt", highlight: "einen Felsen", extra: "ein tiefes Brummen", topicWord: "den Loewen" },
    { title: "Ein Panda aus Papier", topic: "Zoo", theme: "zoo", name: "Elias", friend: "Juna", place: "dem Klassenraum", focus: "den Bambus", item: "schwarzes Tonpapier", tool: "die Schere", highlight: "die Pandazeichnung", extra: "gruene Papierstreifen", topicWord: "den Panda" },
    { title: "Abschied von den Seehunden", topic: "Zoo", theme: "zoo", name: "Luca", friend: "Mama", place: "dem Seehundbecken", focus: "die drehende Schnauze", item: "das Ticket", tool: "den Zooplan", highlight: "einen Wasserball", extra: "ein letztes Winken", topicWord: "den Seehund" },
    { title: "Der lange Geburtstagstisch", topic: "Feier", theme: "birthday", name: "Maja", friend: "Papa", place: "dem Wohnzimmer", focus: "die Torte", item: "bunte Teller", tool: "eine Girlande", highlight: "einen Luftballon", extra: "ein Kerzenpaket", topicWord: "das Geburtstagslied" },
    { title: "Topfschlagen im Flur", topic: "Feier", theme: "birthday", name: "Finn", friend: "Lina", place: "dem Flur", focus: "den Topf", item: "den Kochloeffel", tool: "die Schachtel", highlight: "ein kleines Auto", extra: "ein warmes Kissen", topicWord: "das Spiel" },
    { title: "Die Schatzkarte fuer das Fest", topic: "Feier", theme: "birthday", name: "Tilda", friend: "Paul", place: "dem Garten", focus: "den roten Pfeil", item: "eine Schatzkarte", tool: "die Blechdose", highlight: "eine Muschel", extra: "einen weiteren Hinweis", topicWord: "die Schatzsuche" },
    { title: "Kerzen auf der Torte", topic: "Feier", theme: "birthday", name: "Lara", friend: "Oma", place: "dem Esszimmer", focus: "die Flammen", item: "neun Kerzen", tool: "den Tortenheber", highlight: "ein grosses Stueck", extra: "einen Teller mit Streuseln", topicWord: "das Auspusten" },
    { title: "Das Riesenpaket", topic: "Feier", theme: "birthday", name: "Ben", friend: "Tante", place: "dem Wohnzimmer", focus: "das grosse Geschenk", item: "eine rote Schleife", tool: "die Schere", highlight: "das ferngesteuerte Boot", extra: "eine zweite Schachtel", topicWord: "das Auspacken" },
    { title: "Muffins fuer die Klasse", topic: "Feier", theme: "birthday", name: "Ece", friend: "Mama", place: "der Kueche", focus: "den Kakaoduft", item: "die Muffindose", tool: "die Streuselpackung", highlight: "ein buntes Foermchen", extra: "einen fertigen Muffin", topicWord: "die Geburtstagsmuffins" },
    { title: "Das Geburtstagslied mit Gesten", topic: "Feier", theme: "birthday", name: "Nils", friend: "Jule", place: "dem Morgenkreis", focus: "die schiefe Krone", item: "eine Geburtstagskrone", tool: "die Karte", highlight: "ein breites Lachen", extra: "eine Unterschrift", topicWord: "das Lied" },
    { title: "Schatten an der Gartenwand", topic: "Feier", theme: "birthday", name: "Hedi", friend: "Opa", place: "dem Garten", focus: "den grossen Hasen", item: "eine Taschenlampe", tool: "eine Decke", highlight: "einen Vogel aus Fingern", extra: "eine zweite Lampe", topicWord: "das Schattenspiel" },
    { title: "Die Feier im Vereinshaus", topic: "Feier", theme: "birthday", name: "Rico", friend: "Mila", place: "dem Vereinshaus", focus: "das grosse Paket", item: "Stuhlgirlanden", tool: "die Saftkaraffe", highlight: "einen freien Stuhl", extra: "ein Namensschild", topicWord: "das Fest" },
    { title: "Das Foto mit der Krone", topic: "Feier", theme: "birthday", name: "Nora", friend: "Onkel", place: "der Gartenbank", focus: "den Hund im Bild", item: "die Krone", tool: "die Kamera", highlight: "einen Ausdruck", extra: "ein lustiges Bild", topicWord: "die Erinnerung" },
    { title: "Die Trommelprobe", topic: "Musik", theme: "music", name: "Ben", friend: "Lotte", place: "dem Musikraum", focus: "den Takt", item: "zwei Schlaegel", tool: "die Rassel", highlight: "den lauten Schluss", extra: "einen neuen Einsatz", topicWord: "den Rhythmus" },
    { title: "Ein Lied auf dem Glockenspiel", topic: "Musik", theme: "music", name: "Elif", friend: "Nino", place: "dem Musikraum", focus: "die Notenzeile", item: "das Glockenspiel", tool: "das Notenblatt", highlight: "den hohen Ton", extra: "eine richtige Zeile", topicWord: "die Melodie" },
    { title: "Das Tanzzeichen", topic: "Musik", theme: "music", name: "Marlon", friend: "Tessa", place: "der Turnhalle", focus: "die Lehrerin", item: "die Schrittkarte", tool: "die Musikbox", highlight: "den Schlusskreis", extra: "eine Bewegungsfolge", topicWord: "den Tanz" },
    { title: "Die Floete im Wohnzimmer", topic: "Musik", theme: "music", name: "Sina", friend: "Opa", place: "dem Wohnzimmer", focus: "die schnelle Stelle", item: "die Floete", tool: "das Liedblatt", highlight: "den klaren Ton", extra: "einen Atemtipp", topicWord: "das Ueben" },
    { title: "Ein Rap fuer das Sommerfest", topic: "Musik", theme: "music", name: "Kaya", friend: "Omar", place: "dem AG-Raum", focus: "den Beat", item: "das Reimblatt", tool: "den Stift", highlight: "den Refrain", extra: "eine neue Zeile", topicWord: "den Rap" },
    { title: "Die Geige der Nachbarin", topic: "Musik", theme: "music", name: "Timo", friend: "Nachbarin", place: "dem Hausflur", focus: "die schwingende Saite", item: "den Geigenbogen", tool: "die Geige", highlight: "den ruhigen Teil", extra: "einen Probeton", topicWord: "die Geige" },
    { title: "Das Orchester aus Alltagsdingen", topic: "Musik", theme: "music", name: "Zoe", friend: "Jan", place: "dem Klassenraum", focus: "den neuen Klang", item: "zwei Holzloeffel", tool: "eine Reisdose", highlight: "den Schlussakkord", extra: "ein Zeichen der Lehrerin", topicWord: "das Orchester" },
    { title: "Die Stimme fuers Theaterlied", topic: "Musik", theme: "music", name: "Ava", friend: "Mia", place: "dem Musikraum", focus: "den hohen Ton", item: "das Liedblatt", tool: "die Chorreihe", highlight: "den vollen Klang", extra: "einen sicheren Einsatz", topicWord: "das Theaterlied" },
    { title: "Der Klang der Regenmacher", topic: "Musik", theme: "music", name: "Mika", friend: "Paula", place: "dem Musikraum", focus: "das Rascheln", item: "den Regenmacher", tool: "das Zeichen der Lehrerin", highlight: "die Klangwolke", extra: "ein Stopzeichen", topicWord: "die Klanggeschichte" },
    { title: "Trompetenluft auf dem Schulhof", topic: "Musik", theme: "music", name: "Hannes", friend: "Lara", place: "dem Schulhof", focus: "das Notenblatt", item: "die Trompete", tool: "die Klammermappe", highlight: "die grosse Melodie", extra: "einen zweiten Einsatz", topicWord: "die Probe" },
    { title: "Die Fossilien im Museum", topic: "Forschen", theme: "reading", name: "Malte", friend: "Frau Kern", place: "der Fossilienvitrine", focus: "die Spirale der Schnecke", item: "sein Heft", tool: "den Bleistift", highlight: "den Fischabdruck", extra: "ein Museumszettel", topicWord: "das Fossil" },
    { title: "Der Wochenmarkt am Mittwoch", topic: "Alltag", theme: "family", name: "Emina", friend: "Mama", place: "dem Wochenmarkt", focus: "die Erdbeeren", item: "den Einkaufswagen", tool: "einen Blumenstrauss", highlight: "die gelben Tulpen", extra: "eine Saftprobe", topicWord: "den Markt" },
    { title: "Ein Experiment mit Magneten", topic: "Forschen", theme: "reading", name: "Jonas", friend: "Mira", place: "dem Forschertisch", focus: "die Schere", item: "einen Magneten", tool: "das Ergebnisblatt", highlight: "die Schraube", extra: "einen Holzloeffel", topicWord: "den Magneten" },
    { title: "Mit der Strassenbahn zur Schule", topic: "Alltag", theme: "school", name: "Paul", friend: "Lena", place: "der Strassenbahn", focus: "die nassen Daecher", item: "seinen Ranzen", tool: "die Fahrkarte", highlight: "eine freie Sitzbank", extra: "eine freundliche Dame", topicWord: "die Fahrt" },
    { title: "Der verlorene Handschuh", topic: "Alltag", theme: "playground", name: "Zina", friend: "Oskar", place: "dem Heimweg", focus: "die Bank am Zaun", item: "einen blauen Handschuh", tool: "die Jackentasche", highlight: "etwas Blaues im Gras", extra: "ein kalter Wind", topicWord: "die Suche" },
    { title: "Das Fahrrad in der Werkstatt", topic: "Alltag", theme: "camp", name: "Sami", friend: "Onkel", place: "dem Hof", focus: "die abgesprungene Kette", item: "das Hinterrad", tool: "den Schluessel", highlight: "eine glatte Pedalrunde", extra: "einen Lappen", topicWord: "die Reparatur" },
    { title: "Die Postkarte aus den Ferien", topic: "Alltag", theme: "reading", name: "Emma", friend: "Papa", place: "der Steinmauer am Meer", focus: "die Briefmarke", item: "eine Postkarte", tool: "den Filzstift", highlight: "das Wort Muscheln", extra: "ein fehlender Satz", topicWord: "die Ferienpost" },
    { title: "Die Schneeburg", topic: "Winter", theme: "birthday", name: "Leo", friend: "Mara", place: "dem Hofrand", focus: "die glitzernden Tuerme", item: "einen Eimer Schnee", tool: "eine Lampe", highlight: "eine Zweigfahne", extra: "einen tiefen Eingang", topicWord: "den Schnee" },
    { title: "Der Ausflug zum Planetarium", topic: "Forschen", theme: "school", name: "Nora", friend: "Tim", place: "dem Planetarium", focus: "den Grossen Wagen", item: "ein Sternenblatt", tool: "den Sitzplan", highlight: "den Saturn", extra: "einen neuen Begriff", topicWord: "die Sterne" },
    { title: "Die Muenze im Brunnen", topic: "Alltag", theme: "family", name: "Leonie", friend: "Bruder", place: "dem Marktplatz", focus: "das glitzernde Wasser", item: "eine Muenze", tool: "eine Brezeltuete", highlight: "ein Messingschild", extra: "einen Wunsch", topicWord: "den Brunnen" },
    { title: "Ein Morgen beim Zahnarzt", topic: "Alltag", theme: "family", name: "Karla", friend: "Mama", place: "dem Wartezimmer", focus: "das Aquarium", item: "ihr Heft", tool: "die neue Zahnbuerste", highlight: "den gelben Fisch", extra: "ein Lob", topicWord: "die Kontrolle" },
    { title: "Das Rezept aus dem Kochbuch", topic: "Alltag", theme: "family", name: "Yunis", friend: "Mama", place: "der Kueche", focus: "das alte Kochbuch", item: "einen Korb mit Kartoffeln", tool: "den Schoepfer", highlight: "den Suppenduft", extra: "eine Gemueseknolle", topicWord: "die Suppe" },
    { title: "Der kaputte Regenschirm", topic: "Alltag", theme: "playground", name: "Maya", friend: "Linus", place: "der Bushaltestelle", focus: "die verbogene Strebe", item: "den Regenschirm", tool: "den Druckknopf", highlight: "den starken Wind", extra: "eine trockene Ecke", topicWord: "den Schirm" },
    { title: "Das Spiel im Schaufenster", topic: "Alltag", theme: "reading", name: "Jan", friend: "Kira", place: "dem Schaufenster", focus: "den Baukasten", item: "seinen Wunschzettel", tool: "das Preisschild", highlight: "die kleinen Zahnraeder", extra: "einen Spieletitel", topicWord: "das Spiel" },
    { title: "Die Ritterburg aus Karton", topic: "Basteln", theme: "birthday", name: "Kian", friend: "Ella", place: "dem Werkraum", focus: "den wackligen Turm", item: "einen Schuhkarton", tool: "die Klebeflasche", highlight: "eine Papierfahne", extra: "eine Spielfigur", topicWord: "die Burg" },
    { title: "Die Mineralienkiste", topic: "Forschen", theme: "reading", name: "Sina", friend: "Luca", place: "dem Forschertisch", focus: "den violetten Stein", item: "die Mineralienkiste", tool: "das schwarze Tuch", highlight: "einen glitzernden Rand", extra: "einen langen Namen", topicWord: "das Mineral" },
    { title: "Das Bild im Atelier", topic: "Kunst", theme: "music", name: "Ida", friend: "Frau Neumann", place: "dem Atelier", focus: "den blauen Krug", item: "den grossen Pinsel", tool: "die Farbpalette", highlight: "einen dunklen Schatten", extra: "einen Tropfen Farbe", topicWord: "das Stillleben" },
    { title: "Das Eichhoernchen am Fenster", topic: "Natur", theme: "garden", name: "Theo", friend: "Lehrerin", place: "dem Klassenzimmerfenster", focus: "die Bank im Hof", item: "sein Heft", tool: "den Bleistift", highlight: "den buschigen Schwanz", extra: "eine Nussschale", topicWord: "das Eichhoernchen" },
    { title: "Die Wetterstation auf dem Dach", topic: "Forschen", theme: "school", name: "Mia", friend: "Herr Wolf", place: "der Wetterstation auf dem Schuldach", focus: "den Windmesser", item: "ihr Klemmbrett", tool: "das Messgeraet", highlight: "dunkle Wolken", extra: "ein Tabellenfeld", topicWord: "das Wetter" },
    { title: "Der Flohmarkt im Hof", topic: "Alltag", theme: "playground", name: "Tara", friend: "Jonas", place: "dem Hofmarkt", focus: "die Murmeln auf der Decke", item: "eine Taschenlampe", tool: "den Tauschzettel", highlight: "eine gruene Murmel", extra: "ein Puzzle", topicWord: "den Tausch" }
  ];

  return specs.map(story);
}());


