// Die Rechtschreibpäckchen für das 3. Schuljahr.
//
// Aufbau wie `rechtschreibung.js` (4. Schuljahr): nach Rechtschreibstelle
// sortiert, nicht nach Inhalt, und von Haus aus ausgeblendet. Die Lehrkraft
// schaltet frei, was gerade dran ist.
//
// Diese Liste kommt vom Nutzer und bringt die Formen schon mit — Mehrzahl,
// „du"-Form, Steigerung. Beim Eintragen sind sie einzeln nachgesehen worden;
// die Artikel der Nomen mussten ergänzt werden, die standen nicht dabei.
//
// Drei Stellen, an denen die Zuordnung nicht offensichtlich ist:
//
// * **Trennbare Verben** stehen mit der ganzen „du"-Form da: `anfangen` →
//   „du fängst an". Die Übung zeigt sie genau so, und genau so schreibt man
//   sie auch — getrennt.
// * **`viel` und `gut` sind unregelmäßig gesteigert** (viel → mehr → am
//   meisten). Das Datenfeld nimmt jede Form; gerechnet wird hier nie.
// * **`gern` ist streng genommen ein Adverb**, steht aber in jedem Schulbuch
//   bei der unregelmäßigen Steigerung und ist deshalb als Adjektiv eingetragen.
//   Wer es anders hält, ändert das eine Zeichen.

export const RECHTSCHREIBUNG3 = [
  {
    id: 'k3-doppel-nomen',
    name: 'Doppelkonsonanten — Nomen',
    emoji: '🔡',
    farbe: '#2563eb',
    gruppe: 'rechtschreibung',
    klasse: 3,
    woerter: [
      'Mutter|n|die|Mütter',
      'Sonne|n|die|Sonnen',
      'Ball|n|der|Bälle',
      'Kamm|n|der|Kämme',
      'Puppe|n|die|Puppen',
      'Treppe|n|die|Treppen',
      'Suppe|n|die|Suppen',
      'Hütte|n|die|Hütten',
      'Pfanne|n|die|Pfannen',
      'Tanne|n|die|Tannen',
      'Schwamm|n|der|Schwämme',
      'Stall|n|der|Ställe',
      'Bett|n|das|Betten',
      'Tasse|n|die|Tassen',
      'Brille|n|die|Brillen',
    ],
  },
  {
    id: 'k3-doppel-verben',
    name: 'Doppelkonsonanten — Verben',
    emoji: '🏃',
    farbe: '#1d4ed8',
    gruppe: 'rechtschreibung',
    klasse: 3,
    woerter: [
      'kommen|v|kommst',
      'rennen|v|rennst',
      'kennen|v|kennst',
      'fallen|v|fällst',
      'können|v|kannst',
      'sollen|v|sollst',
      'wollen|v|willst',
      'bellen|v|bellst',
      'füllen|v|füllst',
      'klettern|v|kletterst',
      'hoffen|v|hoffst',
      'schwimmen|v|schwimmst',
      'rollen|v|rollst',
      'stellen|v|stellst',
      'brummen|v|brummst',
    ],
  },
  {
    id: 'k3-doppel-adjektive',
    name: 'Doppelkonsonanten — Adjektive',
    emoji: '🌈',
    farbe: '#0ea5e9',
    gruppe: 'rechtschreibung',
    klasse: 3,
    woerter: [
      'schnell|a|schneller|am schnellsten',
      'dumm|a|dümmer|am dümmsten',
      'dünn|a|dünner|am dünnsten',
      'voll|a|voller|am vollsten',
      'toll|a|toller|am tollsten',
      'hell|a|heller|am hellsten',
      'schlimm|a|schlimmer|am schlimmsten',
      'satt|a|satter|am sattesten',
      'krumm|a|krummer|am krummsten',
      'still|a|stiller|am stillsten',
      'knapp|a|knapper|am knappsten',
      'bitter|a|bitterer|am bittersten',
      'matt|a|matter|am mattesten',
      'fett|a|fetter|am fettesten',
      'schlapp|a|schlapper|am schlappsten',
    ],
  },
  {
    id: 'k3-ck',
    name: 'ck',
    emoji: '🧱',
    farbe: '#38bdf8',
    gruppe: 'rechtschreibung',
    klasse: 3,
    woerter: [
      'Decke|n|die|Decken',
      'Ecke|n|die|Ecken',
      'Jacke|n|die|Jacken',
      'Socke|n|die|Socken',
      'Brücke|n|die|Brücken',
      'Stück|n|das|Stücke',
      'Schnecke|n|die|Schnecken',
      'Glocke|n|die|Glocken',
      'Rucksack|n|der|Rucksäcke',
      'schmecken|v|schmeckst',
      'wecken|v|weckst',
      'packen|v|packst',
      'stecken|v|steckst',
      'dick|a|dicker|am dicksten',
      'lecker|a|leckerer|am leckersten',
    ],
  },
  {
    id: 'k3-tz',
    name: 'tz',
    emoji: '⚡',
    farbe: '#0284c7',
    gruppe: 'rechtschreibung',
    klasse: 3,
    woerter: [
      'Katze|n|die|Katzen',
      'Mütze|n|die|Mützen',
      'Platz|n|der|Plätze',
      'Satz|n|der|Sätze',
      'Blitz|n|der|Blitze',
      'Witz|n|der|Witze',
      'Spitze|n|die|Spitzen',
      'Pfütze|n|die|Pfützen',
      'Netz|n|das|Netze',
      'Schatz|n|der|Schätze',
      'sitzen|v|sitzt',
      'putzen|v|putzt',
      'schwitzen|v|schwitzt',
      'kratzen|v|kratzt',
      'spitz|a|spitzer|am spitzesten',
    ],
  },
  {
    id: 'k3-ie',
    name: 'ie',
    emoji: '🐝',
    farbe: '#f97316',
    gruppe: 'rechtschreibung',
    klasse: 3,
    woerter: [
      'Biene|n|die|Bienen',
      'Wiese|n|die|Wiesen',
      'Brief|n|der|Briefe',
      'Tier|n|das|Tiere',
      'Ziege|n|die|Ziegen',
      'Riese|n|der|Riesen',
      'Lied|n|das|Lieder',
      'Dieb|n|der|Diebe',
      'Fliege|n|die|Fliegen',
      'Zwiebel|n|die|Zwiebeln',
      'spielen|v|spielst',
      'fliegen|v|fliegst',
      'liegen|v|liegst',
      'lieb|a|lieber|am liebsten',
      'tief|a|tiefer|am tiefsten',
    ],
  },
  {
    id: 'k3-dehnungs-h',
    name: 'Dehnungs-h',
    emoji: '🕰️',
    farbe: '#ea580c',
    gruppe: 'rechtschreibung',
    klasse: 3,
    woerter: [
      'Zahn|n|der|Zähne',
      'Jahr|n|das|Jahre',
      'Uhr|n|die|Uhren',
      'Ohr|n|das|Ohren',
      'Stuhl|n|der|Stühle',
      'Kuh|n|die|Kühe',
      'Schuh|n|der|Schuhe',
      'Sohn|n|der|Söhne',
      'Bahn|n|die|Bahnen',
      'Huhn|n|das|Hühner',
      'fahren|v|fährst',
      'wohnen|v|wohnst',
      'fühlen|v|fühlst',
      'zählen|v|zählst',
      'froh|a|froher|am frohesten',
    ],
  },
  {
    id: 'k3-sz',
    name: 'ß',
    emoji: '🦶',
    farbe: '#f59e0b',
    gruppe: 'rechtschreibung',
    klasse: 3,
    woerter: [
      'Fuß|n|der|Füße',
      'Straße|n|die|Straßen',
      'Gruß|n|der|Grüße',
      'Soße|n|die|Soßen',
      'Fußball|n|der|Fußbälle',
      'Strauß|n|der|Sträuße',
      'gießen|v|gießt',
      'grüßen|v|grüßt',
      'schließen|v|schließt',
      'beißen|v|beißt',
      'stoßen|v|stößt',
      'groß|a|größer|am größten',
      'heiß|a|heißer|am heißesten',
      'süß|a|süßer|am süßesten',
      'fleißig|a|fleißiger|am fleißigsten',
    ],
  },
  {
    id: 'k3-ss',
    name: 'ss',
    emoji: '💧',
    farbe: '#eab308',
    gruppe: 'rechtschreibung',
    klasse: 3,
    woerter: [
      'Fluss|n|der|Flüsse',
      'Schloss|n|das|Schlösser',
      'Nuss|n|die|Nüsse',
      'Kuss|n|der|Küsse',
      'Fass|n|das|Fässer',
      'Bus|n|der|Busse',
      'Klasse|n|die|Klassen',
      'Schlüssel|n|der|Schlüssel',
      'Kissen|n|das|Kissen',
      'essen|v|isst',
      'müssen|v|musst',
      'lassen|v|lässt',
      'passen|v|passt',
      'nass|a|nasser|am nassesten',
      'hässlich|a|hässlicher|am hässlichsten',
    ],
  },
  {
    id: 'k3-ableiten',
    name: 'ä / äu ableiten',
    emoji: '🌳',
    farbe: '#2563eb',
    gruppe: 'rechtschreibung',
    klasse: 3,
    // Die Grundform ist das Lernwort, die abgeleitete Form fragt Stufe 4 ab —
    // darum geht es in diesem Päckchen.
    woerter: [
      'Baum|n|der|Bäume',
      'Haus|n|das|Häuser',
      'Maus|n|die|Mäuse',
      'Apfel|n|der|Äpfel',
      'Hand|n|die|Hände',
      'Wand|n|die|Wände',
      'Bank|n|die|Bänke',
      'Rad|n|das|Räder',
      'Glas|n|das|Gläser',
      'Vater|n|der|Väter',
      'Garten|n|der|Gärten',
      'Nagel|n|der|Nägel',
      'laufen|v|läufst',
      'tragen|v|trägst',
      'schlafen|v|schläfst',
    ],
  },
  {
    id: 'k3-auslaut',
    name: 'Auslaut b / d / g',
    emoji: '🐕',
    farbe: '#0369a1',
    gruppe: 'rechtschreibung',
    klasse: 3,
    woerter: [
      'Hund|n|der|Hunde',
      'Kind|n|das|Kinder',
      'Wald|n|der|Wälder',
      'Weg|n|der|Wege',
      'Berg|n|der|Berge',
      'Tag|n|der|Tage',
      'Zug|n|der|Züge',
      'Freund|n|der|Freunde',
      'Korb|n|der|Körbe',
      'Bad|n|das|Bäder',
      'Kleid|n|das|Kleider',
      'Mond|n|der|Monde',
      'Pferd|n|das|Pferde',
      'Bild|n|das|Bilder',
      'wild|a|wilder|am wildesten',
    ],
  },
  {
    id: 'k3-v',
    name: 'Wörter mit V',
    emoji: '🐦',
    farbe: '#1e40af',
    gruppe: 'rechtschreibung',
    klasse: 3,
    woerter: [
      'Vogel|n|der|Vögel',
      'Vase|n|die|Vasen',
      'Volk|n|das|Völker',
      'Vulkan|n|der|Vulkane',
      'Verein|n|der|Vereine',
      'Vorname|n|der|Vornamen',
      'Vorhang|n|der|Vorhänge',
      'Klavier|n|das|Klaviere',
      'Pullover|n|der|Pullover',
      'verstehen|v|verstehst',
      'vergessen|v|vergisst',
      'verlieren|v|verlierst',
      'versuchen|v|versuchst',
      'verkaufen|v|verkaufst',
      'viel|a|mehr|am meisten',
    ],
  },
  {
    id: 'k3-x-chs-ks',
    name: 'x / chs / ks',
    emoji: '🦊',
    farbe: '#c2410c',
    gruppe: 'rechtschreibung',
    klasse: 3,
    woerter: [
      'Hexe|n|die|Hexen',
      'Fuchs|n|der|Füchse',
      'Dachs|n|der|Dachse',
      'Ochse|n|der|Ochsen',
      'Text|n|der|Texte',
      'Taxi|n|das|Taxis',
      'Box|n|die|Boxen',
      'Axt|n|die|Äxte',
      'Keks|n|der|Kekse',
      'Klecks|n|der|Kleckse',
      'Büchse|n|die|Büchsen',
      'wachsen|v|wächst',
      'wechseln|v|wechselst',
      'sechs|x',
      'links|x',
    ],
  },
  {
    id: 'k3-qu-y-c',
    name: 'Qu / y / c',
    emoji: '🪼',
    farbe: '#38bdf8',
    gruppe: 'rechtschreibung',
    klasse: 3,
    woerter: [
      'Quelle|n|die|Quellen',
      'Qualle|n|die|Quallen',
      'Quadrat|n|das|Quadrate',
      'Quark|n|der|-',
      'Baby|n|das|Babys',
      'Hobby|n|das|Hobbys',
      'Handy|n|das|Handys',
      'Pony|n|das|Ponys',
      'Party|n|die|Partys',
      'Computer|n|der|Computer',
      'Clown|n|der|Clowns',
      'quaken|v|quakst',
      'quälen|v|quälst',
      'bequem|a|bequemer|am bequemsten',
      'quer|x',
    ],
  },
  {
    id: 'k3-sp-st',
    name: 'sp / st am Wortanfang',
    emoji: '⭐',
    farbe: '#eab308',
    gruppe: 'rechtschreibung',
    klasse: 3,
    woerter: [
      'Spinne|n|die|Spinnen',
      'Spiel|n|das|Spiele',
      'Stern|n|der|Sterne',
      'Stein|n|der|Steine',
      'Stunde|n|die|Stunden',
      'Strand|n|der|Strände',
      'Stift|n|der|Stifte',
      'Stadt|n|die|Städte',
      'Storch|n|der|Störche',
      'Sport|n|der|-',
      'springen|v|springst',
      'sprechen|v|sprichst',
      'stehen|v|stehst',
      'spät|a|später|am spätesten',
      'stark|a|stärker|am stärksten',
    ],
  },
  {
    id: 'k3-ch',
    name: 'Wörter mit ch',
    emoji: '📖',
    farbe: '#0ea5e9',
    gruppe: 'rechtschreibung',
    klasse: 3,
    woerter: [
      'Buch|n|das|Bücher',
      'Tuch|n|das|Tücher',
      'Kuchen|n|der|Kuchen',
      'Küche|n|die|Küchen',
      'Kirche|n|die|Kirchen',
      'Loch|n|das|Löcher',
      'Dach|n|das|Dächer',
      'Bach|n|der|Bäche',
      'Licht|n|das|Lichter',
      'Milch|n|die|-',
      'machen|v|machst',
      'lachen|v|lachst',
      'kochen|v|kochst',
      'weich|a|weicher|am weichsten',
      'reich|a|reicher|am reichsten',
    ],
  },
  {
    id: 'k3-vorsilben',
    name: 'Vorsilben',
    emoji: '🔎',
    farbe: '#ea580c',
    gruppe: 'rechtschreibung',
    klasse: 3,
    // Die vier trennbaren Verben stehen mit der ganzen „du"-Form da
    // („du fängst an") — getrennt, so wie man sie schreibt.
    woerter: [
      'entdecken|v|entdeckst',
      'erklären|v|erklärst',
      'erzählen|v|erzählst',
      'bekommen|v|bekommst',
      'besuchen|v|besuchst',
      'bezahlen|v|bezahlst',
      'gewinnen|v|gewinnst',
      'gehören|v|gehörst',
      'zerbrechen|v|zerbrichst',
      'verstecken|v|versteckst',
      'anfangen|v|fängst an',
      'aufhören|v|hörst auf',
      'mitnehmen|v|nimmst mit',
      'vorlesen|v|liest vor',
      'Entschuldigung|n|die|Entschuldigungen',
    ],
  },
  {
    id: 'k3-nachsilben-adj',
    name: '-ig / -lich / -isch',
    emoji: '😊',
    farbe: '#facc15',
    gruppe: 'rechtschreibung',
    klasse: 3,
    woerter: [
      'lustig|a|lustiger|am lustigsten',
      'traurig|a|trauriger|am traurigsten',
      'wichtig|a|wichtiger|am wichtigsten',
      'mutig|a|mutiger|am mutigsten',
      'durstig|a|durstiger|am durstigsten',
      'hungrig|a|hungriger|am hungrigsten',
      'schmutzig|a|schmutziger|am schmutzigsten',
      'freundlich|a|freundlicher|am freundlichsten',
      'gefährlich|a|gefährlicher|am gefährlichsten',
      'glücklich|a|glücklicher|am glücklichsten',
      'fröhlich|a|fröhlicher|am fröhlichsten',
      'ehrlich|a|ehrlicher|am ehrlichsten',
      'komisch|a|komischer|am komischsten',
      'frisch|a|frischer|am frischesten',
      'neblig|a|nebliger|am nebligsten',
    ],
  },
  {
    id: 'k3-vokalwechsel',
    name: 'Verben mit Vokalwechsel',
    emoji: '🔁',
    farbe: '#2563eb',
    gruppe: 'rechtschreibung',
    klasse: 3,
    woerter: [
      'geben|v|gibst',
      'lesen|v|liest',
      'helfen|v|hilfst',
      'treffen|v|triffst',
      'werfen|v|wirfst',
      'brechen|v|brichst',
      'waschen|v|wäschst',
      'halten|v|hältst',
      'raten|v|rätst',
      'schlagen|v|schlägst',
      'fangen|v|fängst',
      'messen|v|misst',
      'graben|v|gräbst',
      'blasen|v|bläst',
      'braten|v|brätst',
    ],
  },
  {
    id: 'k3-steigerung',
    name: 'Unregelmäßige Steigerung',
    emoji: '🏆',
    farbe: '#f59e0b',
    gruppe: 'rechtschreibung',
    klasse: 3,
    woerter: [
      'gut|a|besser|am besten',
      'gern|a|lieber|am liebsten',
      'hoch|a|höher|am höchsten',
      'nah|a|näher|am nächsten',
      'alt|a|älter|am ältesten',
      'jung|a|jünger|am jüngsten',
      'lang|a|länger|am längsten',
      'kurz|a|kürzer|am kürzesten',
      'warm|a|wärmer|am wärmsten',
      'kalt|a|kälter|am kältesten',
      'schwach|a|schwächer|am schwächsten',
      'klug|a|klüger|am klügsten',
      'dunkel|a|dunkler|am dunkelsten',
      'teuer|a|teurer|am teuersten',
      'hart|a|härter|am härtesten',
    ],
  },
  {
    id: 'k3-zeit',
    name: 'Wochentage & Zeit',
    emoji: '📅',
    farbe: '#0284c7',
    gruppe: 'rechtschreibung',
    klasse: 3,
    woerter: [
      'Montag|n|der|Montage',
      'Dienstag|n|der|Dienstage',
      'Mittwoch|n|der|Mittwoche',
      'Donnerstag|n|der|Donnerstage',
      'Freitag|n|der|Freitage',
      'Samstag|n|der|Samstage',
      'Sonntag|n|der|Sonntage',
      'Woche|n|die|Wochen',
      'Monat|n|der|Monate',
      'Minute|n|die|Minuten',
      'Sekunde|n|die|Sekunden',
      'Abend|n|der|Abende',
      'Nacht|n|die|Nächte',
      'Mittag|n|der|Mittage',
      'Geburtstag|n|der|Geburtstage',
    ],
  },
  {
    id: 'k3-familie-schule',
    name: 'Familie & Schule',
    emoji: '🏫',
    farbe: '#f97316',
    gruppe: 'rechtschreibung',
    klasse: 3,
    woerter: [
      'Bruder|n|der|Brüder',
      'Schwester|n|die|Schwestern',
      'Tochter|n|die|Töchter',
      'Oma|n|die|Omas',
      'Opa|n|der|Opas',
      'Tante|n|die|Tanten',
      'Onkel|n|der|Onkel',
      'Lehrerin|n|die|Lehrerinnen',
      'Schülerin|n|die|Schülerinnen',
      'Mädchen|n|das|Mädchen',
      'Junge|n|der|Jungen',
      'Hausaufgabe|n|die|Hausaufgaben',
      'Pause|n|die|Pausen',
      'Tafel|n|die|Tafeln',
      'Heft|n|das|Hefte',
    ],
  },
  {
    id: 'k3-merk-1',
    name: 'Merkwörter I',
    emoji: '👻',
    farbe: '#dc2626',
    gruppe: 'rechtschreibung',
    klasse: 3,
    woerter: [
      'vielleicht|x',
      'plötzlich|a||',
      'zusammen|x',
      'nämlich|x',
      'ziemlich|x',
      'wieder|x',
      'endlich|x',
      'Familie|n|die|Familien',
      'Geschichte|n|die|Geschichten',
      'Gespenst|n|das|Gespenster',
      'Fahrrad|n|das|Fahrräder',
      'Arzt|n|der|Ärzte',
      'Kartoffel|n|die|Kartoffeln',
      'Schokolade|n|die|Schokoladen',
      'Kaninchen|n|das|Kaninchen',
    ],
  },
  {
    id: 'k3-merk-2',
    name: 'Merkwörter II — Tiere & Essen',
    emoji: '🍓',
    farbe: '#eab308',
    gruppe: 'rechtschreibung',
    klasse: 3,
    woerter: [
      'Tiger|n|der|Tiger',
      'Löwe|n|der|Löwen',
      'Giraffe|n|die|Giraffen',
      'Elefant|n|der|Elefanten',
      'Krokodil|n|das|Krokodile',
      'Pinguin|n|der|Pinguine',
      'Delfin|n|der|Delfine',
      'Igel|n|der|Igel',
      'Pizza|n|die|Pizzen',
      'Tomate|n|die|Tomaten',
      'Banane|n|die|Bananen',
      'Zitrone|n|die|Zitronen',
      'Kiwi|n|die|Kiwis',
      'Salat|n|der|Salate',
      'Erdbeere|n|die|Erdbeeren',
    ],
  },
  {
    id: 'k3-zahlwoerter',
    name: 'Zahlwörter',
    emoji: '🔢',
    farbe: '#1d4ed8',
    gruppe: 'rechtschreibung',
    klasse: 3,
    woerter: [
      'elf|x',
      'zwölf|x',
      'dreizehn|x',
      'vierzehn|x',
      'fünfzehn|x',
      'sechzehn|x',
      'siebzehn|x',
      'zwanzig|x',
      'dreißig|x',
      'vierzig|x',
      'fünfzig|x',
      'sechzig|x',
      'siebzig|x',
      'hundert|x',
      'tausend|x',
    ],
  },
];
