// Die Rechtschreibblöcke für das 2. Schuljahr.
//
// Aufbau wie `rechtschreibung3.js` und `rechtschreibung.js`, mit zwei
// Unterschieden, die aus der Klassenstufe folgen:
//
// * **Zehn Wörter je Block statt fünfzehn.** Ein Trainingspäckchen ist immer
//   so groß wie der Block; die App rechnet mit der tatsächlichen Zahl und
//   nicht mit einer festen.
// * **Steigerung nur bei einfachen Adjektiven** (Ansage des Nutzers —
//   Steigern ist eher Stoff der 3. Klasse). Wo sie fehlt, stehen leere
//   Felder (`rot|a||`): Das Wort bleibt ein Adjektiv, Stufe 4 fragt die
//   Steigerung nur nicht ab.
//
// Ebenso: **Bei den Wochentagen fehlt die Mehrzahl mit Absicht.** In Klasse 2
// geht es um den Artikel („der Montag"), die Mehrzahl kommt in Klasse 3 dazu
// — dort steht sie auch.

export const RECHTSCHREIBUNG2 = [
  {
    id: 'k2-mitsprech-verben',
    name: 'Mitsprechwörter — Verben',
    emoji: '🗣️',
    farbe: '#2563eb',
    gruppe: 'rechtschreibung',
    klasse: 2,
    woerter: [
      'malen|v|malst',
      'holen|v|holst',
      'sagen|v|sagst',
      'baden|v|badest',
      'reden|v|redest',
      'loben|v|lobst',
      'rufen|v|rufst',
      'singen|v|singst',
      'turnen|v|turnst',
      'weinen|v|weinst',
    ],
  },
  {
    id: 'k2-doppel-nomen',
    name: 'Doppelkonsonanten — Nomen',
    emoji: '🔡',
    farbe: '#1d4ed8',
    gruppe: 'rechtschreibung',
    klasse: 2,
    woerter: [
      'Sommer|n|der|Sommer',
      'Zimmer|n|das|Zimmer',
      'Teller|n|der|Teller',
      'Roller|n|der|Roller',
      'Kette|n|die|Ketten',
      'Affe|n|der|Affen',
      'Mann|n|der|Männer',
      'Kanne|n|die|Kannen',
      'Wanne|n|die|Wannen',
      'Ratte|n|die|Ratten',
    ],
  },
  {
    id: 'k2-doppel-verben',
    name: 'Doppelkonsonanten — Verben & Adjektive',
    emoji: '🐝',
    farbe: '#0ea5e9',
    gruppe: 'rechtschreibung',
    klasse: 2,
    woerter: [
      'kommen|v|kommst',
      'rennen|v|rennst',
      'klappen|v|klappst',
      'summen|v|summst',
      'flattern|v|flatterst',
      'hämmern|v|hämmerst',
      'schwimmen|v|schwimmst',
      'hoffen|v|hoffst',
      'nett|a|netter|am nettesten',
      'schnell|a|schneller|am schnellsten',
    ],
  },
  {
    id: 'k2-ck',
    name: 'ck',
    emoji: '🧱',
    farbe: '#38bdf8',
    gruppe: 'rechtschreibung',
    klasse: 2,
    woerter: [
      'Wecker|n|der|Wecker',
      'Rock|n|der|Röcke',
      'Sack|n|der|Säcke',
      'Stock|n|der|Stöcke',
      'Mücke|n|die|Mücken',
      'Zecke|n|die|Zecken',
      'Bäcker|n|der|Bäcker',
      'Zucker|n|der|-',
      'backen|v|backst',
      'kicken|v|kickst',
    ],
  },
  {
    id: 'k2-tz',
    name: 'tz',
    emoji: '⚡',
    farbe: '#0284c7',
    gruppe: 'rechtschreibung',
    klasse: 2,
    woerter: [
      'Katze|n|die|Katzen',
      'Spatz|n|der|Spatzen',
      'Klotz|n|der|Klötze',
      'Netz|n|das|Netze',
      'Mütze|n|die|Mützen',
      'sitzen|v|sitzt',
      'setzen|v|setzt',
      'spritzen|v|spritzt',
      'schnitzen|v|schnitzt',
      'jetzt|x',
    ],
  },
  {
    id: 'k2-ie',
    name: 'ie',
    emoji: '🌼',
    farbe: '#f97316',
    gruppe: 'rechtschreibung',
    klasse: 2,
    woerter: [
      'Biene|n|die|Bienen',
      'Wiese|n|die|Wiesen',
      'Ziege|n|die|Ziegen',
      'Spiel|n|das|Spiele',
      'Sieb|n|das|Siebe',
      'Ziel|n|das|Ziele',
      'Stiefel|n|der|Stiefel',
      'schieben|v|schiebst',
      'wiegen|v|wiegst',
      'kriechen|v|kriechst',
    ],
  },
  {
    id: 'k2-umlaute',
    name: 'Umlaute ä / ö / ü',
    emoji: '🐻',
    farbe: '#ea580c',
    gruppe: 'rechtschreibung',
    klasse: 2,
    woerter: [
      'Bär|n|der|Bären',
      'Käse|n|der|-',
      'Möhre|n|die|Möhren',
      'Löffel|n|der|Löffel',
      'Tür|n|die|Türen',
      'Bürste|n|die|Bürsten',
      'hören|v|hörst',
      'öffnen|v|öffnest',
      'prüfen|v|prüfst',
      'schön|a|schöner|am schönsten',
    ],
  },
  {
    id: 'k2-ableiten',
    name: 'ä / äu ableiten',
    emoji: '🌳',
    farbe: '#f59e0b',
    gruppe: 'rechtschreibung',
    klasse: 2,
    // Der Nutzer hat den Block selbst „(Mehrzahl)" genannt: Das Lernwort ist
    // die Einzahl, abgeleitet wird in Stufe 4.
    woerter: [
      'Gans|n|die|Gänse',
      'Ast|n|der|Äste',
      'Blatt|n|das|Blätter',
      'Kranz|n|der|Kränze',
      'Schwanz|n|der|Schwänze',
      'Traum|n|der|Träume',
      'Zaun|n|der|Zäune',
      'Raum|n|der|Räume',
      'Bauch|n|der|Bäuche',
      'Laus|n|die|Läuse',
    ],
  },
  {
    id: 'k2-auslaut',
    name: 'Auslaut b / d / g',
    emoji: '🐕',
    farbe: '#0369a1',
    gruppe: 'rechtschreibung',
    klasse: 2,
    woerter: [
      'Hund|n|der|Hunde',
      'Mund|n|der|Münder',
      'Wind|n|der|Winde',
      'Hemd|n|das|Hemden',
      'Feld|n|das|Felder',
      'Held|n|der|Helden',
      'Zwerg|n|der|Zwerge',
      'Krug|n|der|Krüge',
      'Kalb|n|das|Kälber',
      'Stab|n|der|Stäbe',
    ],
  },
  {
    id: 'k2-ei-au-eu',
    name: 'ei / au / eu',
    emoji: '🥚',
    farbe: '#eab308',
    gruppe: 'rechtschreibung',
    klasse: 2,
    woerter: [
      'Ei|n|das|Eier',
      'Seil|n|das|Seile',
      'Feuer|n|das|Feuer',
      'Beule|n|die|Beulen',
      'Raupe|n|die|Raupen',
      'Traube|n|die|Trauben',
      'Daumen|n|der|Daumen',
      'bleiben|v|bleibst',
      'kaufen|v|kaufst',
      'sich freuen|v|freust dich',
    ],
  },
  {
    id: 'k2-sp-st',
    name: 'sp / st',
    emoji: '🥄',
    farbe: '#2563eb',
    gruppe: 'rechtschreibung',
    klasse: 2,
    woerter: [
      'Specht|n|der|Spechte',
      'Spaten|n|der|Spaten',
      'Stufe|n|die|Stufen',
      'Strumpf|n|der|Strümpfe',
      'Stange|n|die|Stangen',
      'sparen|v|sparst',
      'spülen|v|spülst',
      'stampfen|v|stampfst',
      'staunen|v|staunst',
      'stolz|a|stolzer|am stolzesten',
    ],
  },
  {
    id: 'k2-sch',
    name: 'sch',
    emoji: '🐟',
    farbe: '#0ea5e9',
    gruppe: 'rechtschreibung',
    klasse: 2,
    woerter: [
      'Schaf|n|das|Schafe',
      'Schiff|n|das|Schiffe',
      'Schere|n|die|Scheren',
      'Fisch|n|der|Fische',
      'Tisch|n|der|Tische',
      'Tasche|n|die|Taschen',
      'Flasche|n|die|Flaschen',
      'Kirsche|n|die|Kirschen',
      'schreiben|v|schreibst',
      'schneiden|v|schneidest',
    ],
  },
  {
    id: 'k2-ch',
    name: 'ch',
    emoji: '🐉',
    farbe: '#c2410c',
    gruppe: 'rechtschreibung',
    klasse: 2,
    woerter: [
      'Koch|n|der|Köche',
      'Drache|n|der|Drachen',
      'Sache|n|die|Sachen',
      'Becher|n|der|Becher',
      'Eiche|n|die|Eichen',
      'Fach|n|das|Fächer',
      'suchen|v|suchst',
      'brauchen|v|brauchst',
      'riechen|v|riechst',
      'frech|a|frecher|am frechsten',
    ],
  },
  {
    id: 'k2-endungen',
    name: 'Endungen -er / -el / -en',
    emoji: '🪟',
    farbe: '#1e40af',
    gruppe: 'rechtschreibung',
    klasse: 2,
    woerter: [
      'Fenster|n|das|Fenster',
      'Finger|n|der|Finger',
      'Leiter|n|die|Leitern',
      'Feder|n|die|Federn',
      'Esel|n|der|Esel',
      'Nudel|n|die|Nudeln',
      'Schüssel|n|die|Schüsseln',
      'Wagen|n|der|Wagen',
      'Besen|n|der|Besen',
      'Ofen|n|der|Öfen',
    ],
  },
  {
    id: 'k2-v',
    name: 'Wörter mit V',
    emoji: '🐦',
    farbe: '#38bdf8',
    gruppe: 'rechtschreibung',
    klasse: 2,
    woerter: [
      'Vater|n|der|Väter',
      'Vogel|n|der|Vögel',
      'viel|a||',
      'vier|x',
      'von|x',
      'vor|x',
      'vorne|x',
      'voll|a|voller|am vollsten',
      'verlieren|v|verlierst',
      'vergessen|v|vergisst',
    ],
  },
  {
    id: 'k2-dehnungs-h',
    name: 'Dehnungs-h',
    emoji: '🕰️',
    farbe: '#f97316',
    gruppe: 'rechtschreibung',
    klasse: 2,
    woerter: [
      'Uhr|n|die|Uhren',
      'Kuh|n|die|Kühe',
      'Hahn|n|der|Hähne',
      'Fahne|n|die|Fahnen',
      'Bohne|n|die|Bohnen',
      'Höhle|n|die|Höhlen',
      'Mühle|n|die|Mühlen',
      'Zahl|n|die|Zahlen',
      'Mehl|n|das|-',
      'sehr|x',
    ],
  },
  {
    id: 'k2-sz',
    name: 'ß',
    emoji: '🛶',
    farbe: '#eab308',
    gruppe: 'rechtschreibung',
    klasse: 2,
    woerter: [
      'Floß|n|das|Flöße',
      'Kloß|n|der|Klöße',
      'Spaß|n|der|Späße',
      'weiß|a||',
      'draußen|x',
      'außen|x',
      'reißen|v|reißt',
      'schießen|v|schießt',
      'fließen|v|fließt',
      'groß|a|größer|am größten',
    ],
  },
  {
    id: 'k2-ss',
    name: 'ss',
    emoji: '💧',
    farbe: '#0284c7',
    gruppe: 'rechtschreibung',
    klasse: 2,
    woerter: [
      'Wasser|n|das|-',
      'essen|v|isst',
      'Messer|n|das|Messer',
      'Kessel|n|der|Kessel',
      'Sessel|n|der|Sessel',
      'Schuss|n|der|Schüsse',
      'Biss|n|der|Bisse',
      'Riss|n|der|Risse',
      'fressen|v|frisst',
      'küssen|v|küsst',
    ],
  },
  {
    id: 'k2-vokalwechsel',
    name: 'Verben mit Vokalwechsel',
    emoji: '🔁',
    farbe: '#1d4ed8',
    gruppe: 'rechtschreibung',
    klasse: 2,
    woerter: [
      'laufen|v|läufst',
      'fahren|v|fährst',
      'schlafen|v|schläfst',
      'lesen|v|liest',
      'sehen|v|siehst',
      'geben|v|gibst',
      'nehmen|v|nimmst',
      'sprechen|v|sprichst',
      'helfen|v|hilfst',
      'tragen|v|trägst',
    ],
  },
  {
    id: 'k2-adjektive',
    name: 'Adjektive mit Steigerung',
    emoji: '🌈',
    farbe: '#f59e0b',
    gruppe: 'rechtschreibung',
    klasse: 2,
    woerter: [
      'klein|a|kleiner|am kleinsten',
      'laut|a|lauter|am lautesten',
      'leise|a|leiser|am leisesten',
      'langsam|a|langsamer|am langsamsten',
      'sauer|a|saurer|am sauersten',
      'trocken|a|trockener|am trockensten',
      'schwer|a|schwerer|am schwersten',
      'leicht|a|leichter|am leichtesten',
      'müde|a|müder|am müdesten',
      'neu|a|neuer|am neuesten',
    ],
  },
  {
    id: 'k2-tiere',
    name: 'Tiere',
    emoji: '🦉',
    farbe: '#0369a1',
    gruppe: 'rechtschreibung',
    klasse: 2,
    woerter: [
      'Ente|n|die|Enten',
      'Hase|n|der|Hasen',
      'Frosch|n|der|Frösche',
      'Wurm|n|der|Würmer',
      'Schwein|n|das|Schweine',
      'Eule|n|die|Eulen',
      'Rabe|n|der|Raben',
      'Reh|n|das|Rehe',
      'Wolf|n|der|Wölfe',
      'Hamster|n|der|Hamster',
    ],
  },
  {
    id: 'k2-koerper',
    name: 'Körper',
    emoji: '🦶',
    farbe: '#dc2626',
    gruppe: 'rechtschreibung',
    klasse: 2,
    woerter: [
      'Kopf|n|der|Köpfe',
      'Haar|n|das|Haare',
      'Auge|n|das|Augen',
      'Hals|n|der|Hälse',
      'Arm|n|der|Arme',
      'Bein|n|das|Beine',
      'Zeh|n|der|Zehen',
      'Herz|n|das|Herzen',
      'Zunge|n|die|Zungen',
      'Lippe|n|die|Lippen',
    ],
  },
  {
    id: 'k2-kleidung',
    name: 'Kleidung',
    emoji: '🧥',
    farbe: '#ea580c',
    gruppe: 'rechtschreibung',
    klasse: 2,
    woerter: [
      'Hut|n|der|Hüte',
      'Schal|n|der|Schals',
      'Mantel|n|der|Mäntel',
      'Bluse|n|die|Blusen',
      'Handschuh|n|der|Handschuhe',
      'Gürtel|n|der|Gürtel',
      'Knopf|n|der|Knöpfe',
      'Sandale|n|die|Sandalen',
      'Weste|n|die|Westen',
      'Kappe|n|die|Kappen',
    ],
  },
  {
    id: 'k2-wetter',
    name: 'Wetter & Jahreszeiten',
    emoji: '🌦️',
    farbe: '#38bdf8',
    gruppe: 'rechtschreibung',
    klasse: 2,
    woerter: [
      'Frühling|n|der|-',
      'Herbst|n|der|-',
      'Winter|n|der|-',
      'Regen|n|der|-',
      'Schnee|n|der|-',
      'Wolke|n|die|Wolken',
      'Sturm|n|der|Stürme',
      'Donner|n|der|-',
      'Nebel|n|der|-',
      'Eis|n|das|-',
    ],
  },
  {
    id: 'k2-zeit',
    name: 'Wochentage & Zeit',
    emoji: '📅',
    farbe: '#0ea5e9',
    gruppe: 'rechtschreibung',
    klasse: 2,
    // Ohne Mehrzahl: In Klasse 2 geht es um den Artikel („der Montag"),
    // die Mehrzahl kommt im Klasse-3-Päckchen dazu.
    woerter: [
      'Montag|n|der|-',
      'Dienstag|n|der|-',
      'Mittwoch|n|der|-',
      'Donnerstag|n|der|-',
      'Freitag|n|der|-',
      'Samstag|n|der|-',
      'Sonntag|n|der|-',
      'gestern|x',
      'heute|x',
      'morgen|x',
    ],
  },
  {
    id: 'k2-zahlen',
    name: 'Zahlen',
    emoji: '🔢',
    farbe: '#2563eb',
    gruppe: 'rechtschreibung',
    klasse: 2,
    woerter: [
      'eins|x',
      'zwei|x',
      'drei|x',
      'vier|x',
      'fünf|x',
      'sechs|x',
      'sieben|x',
      'acht|x',
      'neun|x',
      'zehn|x',
    ],
  },
  {
    id: 'k2-farben',
    name: 'Farben',
    emoji: '🎨',
    farbe: '#facc15',
    gruppe: 'rechtschreibung',
    klasse: 2,
    // Farbwörter sind Adjektive; gesteigert wird in Klasse 2 noch nicht.
    woerter: [
      'rot|a||',
      'blau|a||',
      'gelb|a||',
      'grün|a||',
      'schwarz|a||',
      'braun|a||',
      'rosa|a||',
      'lila|a||',
      'grau|a||',
      'orange|a||',
    ],
  },
  {
    id: 'k2-funktionswoerter',
    name: 'Funktionswörter',
    emoji: '🔗',
    farbe: '#94a3b8',
    gruppe: 'rechtschreibung',
    klasse: 2,
    woerter: [
      'und|x',
      'ist|x',
      'sind|x',
      'mit|x',
      'auf|x',
      'nicht|x',
      'auch|x',
      'dann|x',
      'noch|x',
      'aber|x',
    ],
  },
];
