// Die Rechtschreibblöcke für das 1. Schuljahr.
//
// Dreiundzwanzig Blöcke zu je acht Wörtern, überwiegend lautgetreu. Drei
// Dinge unterscheiden sie von den höheren Klassenstufen:
//
// * **Keine Wortart-Stufe.** Ob ein Wort Nomen, Verb oder Adjektiv ist, ist
//   noch kein Stoff der 1. Klasse (Ansage des Nutzers). Der Block sagt das
//   über `stufen` — und die App lässt Stufe 4 dann weg, statt sie mit einer
//   Frage zu füllen, die niemand beantworten kann.
// * **Keine „du"-Form und keine Steigerung.** Verben stehen mit leerem Feld
//   (`toben|v|`), Adjektive mit zwei leeren (`bunt|a||`). Die Wortart bleibt
//   trotzdem richtig eingetragen: Sie färbt den Wortschnipsel in der
//   Übersicht und den Hinweis beim Diktat.
// * **Acht Wörter je Block.** Ein Trainingspäckchen ist so groß wie sein
//   Bereich.
//
// Die Mehrzahlen aus der Liste stehen mit in den Daten, obwohl Stufe 4 hier
// aus ist. Sie sind richtig, sie kosten nichts — und wer den Block später
// doch mit Wortarten üben lassen will, streicht eine Zeile.

// Welche Stufen dieser Jahrgang übt. Stufe 4 („wortart") fehlt mit Absicht.
const STUFEN_KLASSE_1 = ['abschreiben', 'salat', 'geheimschrift', 'diktat'];

export const RECHTSCHREIBUNG1 = [
  {
    id: 'k1-erste-woerter',
    name: 'Erste Wörter',
    emoji: '👶',
    farbe: '#2563eb',
    gruppe: 'rechtschreibung',
    klasse: 1,
    stufen: STUFEN_KLASSE_1,
    woerter: [
      'Mama|n|die|Mamas',
      'Papa|n|der|Papas',
      'Oma|n|die|Omas',
      'Opa|n|der|Opas',
      'Nase|n|die|Nasen',
      'Hose|n|die|Hosen',
      'Rose|n|die|Rosen',
      'Dose|n|die|Dosen',
    ],
  },
  {
    id: 'k1-endung-el',
    name: 'Endung -el',
    emoji: '🪡',
    farbe: '#1d4ed8',
    gruppe: 'rechtschreibung',
    klasse: 1,
    stufen: STUFEN_KLASSE_1,
    woerter: [
      'Gabel|n|die|Gabeln',
      'Nadel|n|die|Nadeln',
      'Kugel|n|die|Kugeln',
      'Segel|n|das|Segel',
      'Ampel|n|die|Ampeln',
      'Igel|n|der|Igel',
      'Kegel|n|der|Kegel',
      'Insel|n|die|Inseln',
    ],
  },
  {
    id: 'k1-endung-er',
    name: 'Endung -er',
    emoji: '🪣',
    farbe: '#0ea5e9',
    gruppe: 'rechtschreibung',
    klasse: 1,
    stufen: STUFEN_KLASSE_1,
    woerter: [
      'Eimer|n|der|Eimer',
      'Kater|n|der|Kater',
      'Mauer|n|die|Mauern',
      'Ufer|n|das|Ufer',
      'Bauer|n|der|Bauern',
      'Ruder|n|das|Ruder',
      'Adler|n|der|Adler',
      'Hafer|n|der|-',
    ],
  },
  {
    id: 'k1-endung-en',
    name: 'Endung -en',
    emoji: '🌳',
    farbe: '#38bdf8',
    gruppe: 'rechtschreibung',
    klasse: 1,
    stufen: STUFEN_KLASSE_1,
    woerter: [
      'Garten|n|der|Gärten',
      'Boden|n|der|Böden',
      'Faden|n|der|Fäden',
      'Laden|n|der|Läden',
      'Hafen|n|der|Häfen',
      'Reifen|n|der|Reifen',
      'Magen|n|der|Mägen',
      'Rasen|n|der|-',
    ],
  },
  {
    id: 'k1-tunwoerter',
    name: 'Tunwörter',
    emoji: '🏃',
    farbe: '#0284c7',
    gruppe: 'rechtschreibung',
    klasse: 1,
    stufen: STUFEN_KLASSE_1,
    woerter: [
      'toben|v|',
      'fragen|v|',
      'jagen|v|',
      'kleben|v|',
      'leben|v|',
      'raten|v|',
      'nagen|v|',
      'beten|v|',
    ],
  },
  {
    id: 'k1-wiewoerter',
    name: 'Wiewörter',
    emoji: '🌈',
    farbe: '#f97316',
    gruppe: 'rechtschreibung',
    klasse: 1,
    stufen: STUFEN_KLASSE_1,
    woerter: [
      'bunt|a||',
      'rund|a||',
      'brav|a||',
      'fein|a||',
      'sauber|a||',
      'kühl|a||',
      'böse|a||',
      'faul|a||',
    ],
  },
  {
    id: 'k1-au-ei-eu',
    name: 'au / ei / eu',
    emoji: '🚗',
    farbe: '#ea580c',
    gruppe: 'rechtschreibung',
    klasse: 1,
    stufen: STUFEN_KLASSE_1,
    woerter: [
      'Auto|n|das|Autos',
      'Baum|n|der|Bäume',
      'Haus|n|das|Häuser',
      'Maus|n|die|Mäuse',
      'Seife|n|die|Seifen',
      'Reise|n|die|Reisen',
      'Eis|n|das|-',
      'neun|x',
    ],
  },
  {
    id: 'k1-umlaute',
    name: 'Umlaute ä / ö / ü',
    emoji: '🦁',
    farbe: '#f59e0b',
    gruppe: 'rechtschreibung',
    klasse: 1,
    stufen: STUFEN_KLASSE_1,
    woerter: [
      'Löwe|n|der|Löwen',
      'Käfer|n|der|Käfer',
      'Möwe|n|die|Möwen',
      'Hügel|n|der|Hügel',
      'Rübe|n|die|Rüben',
      'Säge|n|die|Sägen',
      'Kübel|n|der|Kübel',
      'Öl|n|das|-',
    ],
  },
  {
    id: 'k1-mitlaute-anfang',
    name: 'Zwei Mitlaute am Anfang',
    emoji: '🌷',
    farbe: '#eab308',
    gruppe: 'rechtschreibung',
    klasse: 1,
    stufen: STUFEN_KLASSE_1,
    woerter: [
      'Blume|n|die|Blumen',
      'Brot|n|das|Brote',
      'Glas|n|das|Gläser',
      'Kran|n|der|Kräne',
      'Krone|n|die|Kronen',
      'Flöte|n|die|Flöten',
      'Pflaume|n|die|Pflaumen',
      'Zweig|n|der|Zweige',
    ],
  },
  {
    id: 'k1-mitlaute-ende',
    name: 'Zwei Mitlaute am Ende',
    emoji: '⛺',
    farbe: '#2563eb',
    gruppe: 'rechtschreibung',
    klasse: 1,
    stufen: STUFEN_KLASSE_1,
    woerter: [
      'Zelt|n|das|Zelte',
      'Wurst|n|die|Würste',
      'Pilz|n|der|Pilze',
      'Holz|n|das|-',
      'Salz|n|das|-',
      'Ring|n|der|Ringe',
      'Elch|n|der|Elche',
      'Tank|n|der|Tanks',
    ],
  },
  {
    id: 'k1-sch',
    name: 'sch',
    emoji: '🐚',
    farbe: '#0369a1',
    gruppe: 'rechtschreibung',
    klasse: 1,
    stufen: STUFEN_KLASSE_1,
    woerter: [
      'Schule|n|die|Schulen',
      'Schuh|n|der|Schuhe',
      'Schaukel|n|die|Schaukeln',
      'Schaufel|n|die|Schaufeln',
      'Schlange|n|die|Schlangen',
      'Schwan|n|der|Schwäne',
      'Dusche|n|die|Duschen',
      'Muschel|n|die|Muscheln',
    ],
  },
  {
    id: 'k1-ch',
    name: 'ch',
    emoji: '📖',
    farbe: '#1e40af',
    gruppe: 'rechtschreibung',
    klasse: 1,
    stufen: STUFEN_KLASSE_1,
    woerter: [
      'ich|x',
      'mich|x',
      'dich|x',
      'doch|x',
      'Buch|n|das|Bücher',
      'Milch|n|die|-',
      'Rauch|n|der|-',
      'Schlauch|n|der|Schläuche',
    ],
  },
  {
    id: 'k1-st-sp',
    name: 'st / sp',
    emoji: '⭐',
    farbe: '#38bdf8',
    gruppe: 'rechtschreibung',
    klasse: 1,
    stufen: STUFEN_KLASSE_1,
    woerter: [
      'Stern|n|der|Sterne',
      'Stein|n|der|Steine',
      'Stift|n|der|Stifte',
      'Stuhl|n|der|Stühle',
      'Star|n|der|Stare',
      'Spiel|n|das|Spiele',
      'Spinne|n|die|Spinnen',
      'Spur|n|die|Spuren',
    ],
  },
  {
    id: 'k1-ie',
    name: 'ie',
    emoji: '🐝',
    farbe: '#f97316',
    gruppe: 'rechtschreibung',
    klasse: 1,
    stufen: STUFEN_KLASSE_1,
    woerter: [
      'Biene|n|die|Bienen',
      'Wiese|n|die|Wiesen',
      'Ziege|n|die|Ziegen',
      'Riese|n|der|Riesen',
      'Tier|n|das|Tiere',
      'Knie|n|das|Knie',
      'Wiege|n|die|Wiegen',
      'Liebe|n|die|-',
    ],
  },
  {
    id: 'k1-doppel',
    name: 'Doppelkonsonanten',
    emoji: '☀️',
    farbe: '#eab308',
    gruppe: 'rechtschreibung',
    klasse: 1,
    stufen: STUFEN_KLASSE_1,
    woerter: [
      'Mutter|n|die|Mütter',
      'Sonne|n|die|Sonnen',
      'Puppe|n|die|Puppen',
      'Ball|n|der|Bälle',
      'Bett|n|das|Betten',
      'Hallo|x',
      'alle|x',
      'immer|x',
    ],
  },
  {
    id: 'k1-v-dehnung',
    name: 'Merkwörter V & Dehnungs-h',
    emoji: '🐦',
    farbe: '#0284c7',
    gruppe: 'rechtschreibung',
    klasse: 1,
    stufen: STUFEN_KLASSE_1,
    woerter: [
      'Vater|n|der|Väter',
      'Vogel|n|der|Vögel',
      'vier|x',
      'viel|a||',
      'Uhr|n|die|Uhren',
      'Ohr|n|das|Ohren',
      'Zahn|n|der|Zähne',
      'Kuh|n|die|Kühe',
    ],
  },
  {
    id: 'k1-sz-ck-tz',
    name: 'Merkwörter ß, ck & tz',
    emoji: '🦶',
    farbe: '#ea580c',
    gruppe: 'rechtschreibung',
    klasse: 1,
    stufen: STUFEN_KLASSE_1,
    woerter: [
      'groß|a||',
      'Fuß|n|der|Füße',
      'heiß|a||',
      'weiß|a||',
      'Katze|n|die|Katzen',
      'Zucker|n|der|-',
      'Ecke|n|die|Ecken',
      'Socke|n|die|Socken',
    ],
  },
  {
    id: 'k1-funktion-1',
    name: 'Funktionswörter I',
    emoji: '🔗',
    farbe: '#94a3b8',
    gruppe: 'rechtschreibung',
    klasse: 1,
    stufen: STUFEN_KLASSE_1,
    woerter: ['der|x', 'die|x', 'das|x', 'ein|x', 'eine|x', 'in|x', 'im|x', 'am|x'],
  },
  {
    id: 'k1-funktion-2',
    name: 'Funktionswörter II',
    emoji: '🔗',
    farbe: '#94a3b8',
    gruppe: 'rechtschreibung',
    klasse: 1,
    stufen: STUFEN_KLASSE_1,
    woerter: ['du|x', 'er|x', 'sie|x', 'es|x', 'wir|x', 'hat|x', 'kann|x', 'will|x'],
  },
  {
    id: 'k1-funktion-3',
    name: 'Funktionswörter III',
    emoji: '🔗',
    farbe: '#94a3b8',
    gruppe: 'rechtschreibung',
    klasse: 1,
    stufen: STUFEN_KLASSE_1,
    woerter: ['und|x', 'ist|x', 'ja|x', 'nein|x', 'da|x', 'wo|x', 'was|x', 'wer|x'],
  },
  {
    id: 'k1-tiere',
    name: 'Tiere',
    emoji: '🐼',
    farbe: '#0369a1',
    gruppe: 'rechtschreibung',
    klasse: 1,
    stufen: STUFEN_KLASSE_1,
    woerter: [
      'Uhu|n|der|Uhus',
      'Wal|n|der|Wale',
      'Lama|n|das|Lamas',
      'Panda|n|der|Pandas',
      'Kamel|n|das|Kamele',
      'Zebra|n|das|Zebras',
      'Koala|n|der|Koalas',
      'Kakadu|n|der|Kakadus',
    ],
  },
  {
    id: 'k1-essen',
    name: 'Essen',
    emoji: '🍈',
    farbe: '#f59e0b',
    gruppe: 'rechtschreibung',
    klasse: 1,
    stufen: STUFEN_KLASSE_1,
    woerter: [
      'Birne|n|die|Birnen',
      'Melone|n|die|Melonen',
      'Gurke|n|die|Gurken',
      'Salami|n|die|Salamis',
      'Kakao|n|der|-',
      'Honig|n|der|-',
      'Reis|n|der|-',
      'Mais|n|der|-',
    ],
  },
  {
    id: 'k1-schule',
    name: 'Schule',
    emoji: '🎒',
    farbe: '#2563eb',
    gruppe: 'rechtschreibung',
    klasse: 1,
    stufen: STUFEN_KLASSE_1,
    woerter: [
      'Heft|n|das|Hefte',
      'Tafel|n|die|Tafeln',
      'Kreide|n|die|-',
      'Mappe|n|die|Mappen',
      'Tornister|n|der|Tornister',
      'Lineal|n|das|Lineale',
      'Kleber|n|der|Kleber',
      'Pinsel|n|der|Pinsel',
    ],
  },
];
