// Die Rechtschreibblöcke für das 4. Schuljahr.
//
// Für das 3. Schuljahr gibt es `rechtschreibung3.js` — gleicher Aufbau,
// eigene Wortliste, ebenfalls von Haus aus ausgeblendet.
//
// Anders als die zwanzig Themenbereiche in `woerter.js` sind diese nicht nach
// Inhalt sortiert, sondern nach der **Rechtschreibstelle**: alle Wörter eines
// Blocks tragen dasselbe Problem. Genau so stehen Lernwörter im Sprachbuch —
// „diese Woche üben wir die Doppelkonsonanten", nicht „diese Woche üben wir
// Tiere".
//
// Sie sind **von Haus aus ausgeblendet** und werden von der Lehrkraft
// zugeschaltet (Einstellungen → Bereiche wählen). Siebenundzwanzig zusätzliche
// Karten auf der Startseite wären für ein Kind, das eine Woche lang einen
// einzigen Block übt, nur Gestrüpp.
//
// Format wie in `woerter.js`. Die Wortarten und die Formen sind von Hand
// bestimmt und nicht gerechnet — warum, steht in `grammatik.js`.
//
// Drei Entscheidungen, die man beim Lesen sonst für Nachlässigkeit hält:
//
// 1. **Wo die Rechtschreibstelle erst in der ABGELEITETEN Form steckt, steht
//    die Grundform als Lernwort** (Block „ä/äu ableiten": `Baum|n|der|Bäume`,
//    nicht `Bäume`). Das ist der Sinn des Blocks: Man leitet ab. Stufe 4 fragt
//    genau diese Ableitung ab — Einzahl → Mehrzahl, Grundform → „du"-Form.
//    Dasselbe beim silbentrennenden h (`Schuh` → `Schuhe`, `früh` → `früher`).
// 2. **Nicht steigerbare Adjektive haben leere Steigerungsfelder**
//    (`wahr|a||`). Stufe 4 fragt sie dann nicht ab, statt eine Form zu
//    verlangen, die es nicht gibt.
// 3. **Wortgruppen sind „keines davon"** (`beim Essen|x`). Sie sind kein
//    Nomen — im Block „Großschreibung" geht es um die Großschreibung, und die
//    prüfen die Stufen 1, 2, 3 und 5 ohnehin buchstabengenau.

export const RECHTSCHREIBUNG = [
  {
    id: 'rs-doppel-1',
    name: 'Doppelkonsonanten I',
    emoji: '🔡',
    farbe: '#2563eb',
    gruppe: 'rechtschreibung',
    klasse: 4,
    woerter: [
      'Mutter|n|die|Mütter',
      'Sommer|n|der|Sommer',
      'Sonne|n|die|Sonnen',
      'kommen|v|kommst',
      'schnell|a|schneller|am schnellsten',
      'immer|x',
      'alle|x',
      'dumm|a|dümmer|am dümmsten',
      'Himmel|n|der|Himmel',
      'Zimmer|n|das|Zimmer',
      'Butter|n|die|-',
      'Kamm|n|der|Kämme',
      'voll|a|voller|am vollsten',
      'toll|a|toller|am tollsten',
      'Ball|n|der|Bälle',
    ],
  },
  {
    id: 'rs-doppel-2',
    name: 'Doppelkonsonanten II',
    emoji: '🔠',
    farbe: '#1d4ed8',
    gruppe: 'rechtschreibung',
    klasse: 4,
    woerter: [
      'fallen|v|fällst',
      'sollen|v|sollst',
      'wollen|v|willst',
      'rennen|v|rennst',
      'kennen|v|kennst',
      'Treppe|n|die|Treppen',
      'Teller|n|der|Teller',
      'Suppe|n|die|Suppen',
      'Puppe|n|die|Puppen',
      'dünn|a|dünner|am dünnsten',
      'Hütte|n|die|Hütten',
      'Nummer|n|die|Nummern',
      'Pfanne|n|die|Pfannen',
      'Wolle|n|die|-',
      'bitte|x',
    ],
  },
  {
    id: 'rs-ck',
    name: 'ck',
    emoji: '🧱',
    farbe: '#0ea5e9',
    gruppe: 'rechtschreibung',
    klasse: 4,
    woerter: [
      'Rucksack|n|der|Rucksäcke',
      'Decke|n|die|Decken',
      'Ecke|n|die|Ecken',
      'Glück|n|das|-',
      'Stück|n|das|Stücke',
      'Zucker|n|der|-',
      'backen|v|bäckst',
      'schmecken|v|schmeckst',
      'wecken|v|weckst',
      'Brücke|n|die|Brücken',
      'Jacke|n|die|Jacken',
      'Socke|n|die|Socken',
      'dick|a|dicker|am dicksten',
      'Rücken|n|der|Rücken',
      'packen|v|packst',
    ],
  },
  {
    id: 'rs-tz',
    name: 'tz',
    emoji: '⚡',
    farbe: '#38bdf8',
    gruppe: 'rechtschreibung',
    klasse: 4,
    woerter: [
      'sitzen|v|sitzt',
      'Platz|n|der|Plätze',
      'Schatz|n|der|Schätze',
      'Katze|n|die|Katzen',
      'Satz|n|der|Sätze',
      'jetzt|x',
      'Mütze|n|die|Mützen',
      'Blitz|n|der|Blitze',
      'Spitze|n|die|Spitzen',
      'putzen|v|putzt',
      'schmutzig|a|schmutziger|am schmutzigsten',
      'trotzdem|x',
      'Witz|n|der|Witze',
      'Hitze|n|die|-',
      'Pfütze|n|die|Pfützen',
    ],
  },
  {
    id: 'rs-ie',
    name: 'ie',
    emoji: '🐝',
    farbe: '#0284c7',
    gruppe: 'rechtschreibung',
    klasse: 4,
    woerter: [
      'spielen|v|spielst',
      'Biene|n|die|Bienen',
      'Wiese|n|die|Wiesen',
      'Brief|n|der|Briefe',
      'lieb|a|lieber|am liebsten',
      'liegen|v|liegst',
      'fliegen|v|fliegst',
      'Tier|n|das|Tiere',
      'nie|x',
      'Papier|n|das|Papiere',
      'Spiegel|n|der|Spiegel',
      'Ziege|n|die|Ziegen',
      'Riese|n|der|Riesen',
      'Stiefel|n|der|Stiefel',
      'Knie|n|das|Knie',
    ],
  },
  {
    id: 'rs-dehnung-1',
    name: 'Dehnungs-h I',
    emoji: '🕰️',
    farbe: '#f97316',
    gruppe: 'rechtschreibung',
    klasse: 4,
    woerter: [
      'fahren|v|fährst',
      'Fahrrad|n|das|Fahrräder',
      'Jahr|n|das|Jahre',
      'Uhr|n|die|Uhren',
      'Ohr|n|das|Ohren',
      'wohnen|v|wohnst',
      'nehmen|v|nimmst',
      'Lehrer|n|der|Lehrer',
      'Zahn|n|der|Zähne',
      'zählen|v|zählst',
      'fühlen|v|fühlst',
      'Zahl|n|die|Zahlen',
      'Fehler|n|der|Fehler',
      'Stuhl|n|der|Stühle',
      'ohne|x',
    ],
  },
  {
    id: 'rs-dehnung-2',
    name: 'Dehnungs-h II',
    emoji: '🐄',
    farbe: '#ea580c',
    gruppe: 'rechtschreibung',
    klasse: 4,
    woerter: [
      'Sohn|n|der|Söhne',
      'Kuh|n|die|Kühe',
      'Bahn|n|die|Bahnen',
      'Mehl|n|das|-',
      'ihr|x',
      'ihm|x',
      'sehr|x',
      'Schuh|n|der|Schuhe',
      'Höhle|n|die|Höhlen',
      'zehn|x',
      'Wohnung|n|die|Wohnungen',
      'Hahn|n|der|Hähne',
      'Fahne|n|die|Fahnen',
      'Bühne|n|die|Bühnen',
      'Sahne|n|die|-',
    ],
  },
  {
    id: 'rs-aa-ee-oo',
    name: 'aa · ee · oo',
    emoji: '🫖',
    farbe: '#f59e0b',
    gruppe: 'rechtschreibung',
    klasse: 4,
    woerter: [
      'Haar|n|das|Haare',
      'Paar|n|das|Paare',
      'Saal|n|der|Säle',
      'Staat|n|der|Staaten',
      'Waage|n|die|Waagen',
      'See|n|der|Seen',
      'Tee|n|der|Tees',
      'Schnee|n|der|-',
      'Beere|n|die|Beeren',
      'Klee|n|der|-',
      'Idee|n|die|Ideen',
      'Fee|n|die|Feen',
      'Boot|n|das|Boote',
      'Moos|n|das|Moose',
      'Zoo|n|der|Zoos',
    ],
  },
  {
    id: 'rs-sz',
    name: 'ß',
    emoji: '🦶',
    farbe: '#eab308',
    gruppe: 'rechtschreibung',
    klasse: 4,
    woerter: [
      'groß|a|größer|am größten',
      'Fuß|n|der|Füße',
      'heiß|a|heißer|am heißesten',
      'weiß|a|weißer|am weißesten',
      'Straße|n|die|Straßen',
      'draußen|x',
      'Spaß|n|der|Späße',
      'süß|a|süßer|am süßesten',
      'fleißig|a|fleißiger|am fleißigsten',
      'schließen|v|schließt',
      'außen|x',
      'grüßen|v|grüßt',
      'gießen|v|gießt',
      'beißen|v|beißt',
      'Fußball|n|der|Fußbälle',
    ],
  },
  {
    id: 'rs-ss',
    name: 'ss',
    emoji: '💧',
    farbe: '#facc15',
    gruppe: 'rechtschreibung',
    klasse: 4,
    woerter: [
      'essen|v|isst',
      'Wasser|n|das|-',
      'Klasse|n|die|Klassen',
      'wissen|v|weißt',
      'lassen|v|lässt',
      'müssen|v|musst',
      'bisschen|x',
      'Schloss|n|das|Schlösser',
      'Fluss|n|der|Flüsse',
      'Schluss|n|der|Schlüsse',
      'Kissen|n|das|Kissen',
      'Nuss|n|die|Nüsse',
      'nass|a|nasser|am nassesten',
      'hässlich|a|hässlicher|am hässlichsten',
      'Schlüssel|n|der|Schlüssel',
    ],
  },
  {
    id: 'rs-ableiten',
    name: 'ä / äu ableiten',
    emoji: '🌳',
    farbe: '#2563eb',
    gruppe: 'rechtschreibung',
    klasse: 4,
    // Hier steht mit Absicht die GRUNDFORM als Lernwort: Der Block heißt
    // „ableiten", und abgeleitet wird in Stufe 4 (Baum → die Bäume, laufen →
    // du läufst). Stünde „Bäume" als Lernwort da, gäbe es nichts abzuleiten.
    woerter: [
      'Baum|n|der|Bäume',
      'Haus|n|das|Häuser',
      'Maus|n|die|Mäuse',
      'laufen|v|läufst',
      'träumen|v|träumst',
      'Glas|n|das|Gläser',
      'Apfel|n|der|Äpfel',
      'Hand|n|die|Hände',
      'Zahn|n|der|Zähne',
      'Mann|n|der|Männer',
      'Garten|n|der|Gärten',
      'Wand|n|die|Wände',
      'Bank|n|die|Bänke',
      'Rad|n|das|Räder',
      'fahren|v|fährst',
    ],
  },
  {
    id: 'rs-auslaut',
    name: 'Auslaut b / d / g',
    emoji: '🐕',
    farbe: '#0369a1',
    gruppe: 'rechtschreibung',
    klasse: 4,
    woerter: [
      'Hund|n|der|Hunde',
      'Kind|n|das|Kinder',
      'Hand|n|die|Hände',
      'Wald|n|der|Wälder',
      'Weg|n|der|Wege',
      'Berg|n|der|Berge',
      'Tag|n|der|Tage',
      'Zug|n|der|Züge',
      'Freund|n|der|Freunde',
      'Geld|n|das|-',
      'gelb|a|gelber|am gelbsten',
      'Rad|n|das|Räder',
      'Bad|n|das|Bäder',
      'Korb|n|der|Körbe',
      'Dieb|n|der|Diebe',
    ],
  },
  {
    id: 'rs-v',
    name: 'Wörter mit V',
    emoji: '🐦',
    farbe: '#1e40af',
    gruppe: 'rechtschreibung',
    klasse: 4,
    woerter: [
      'Vater|n|der|Väter',
      'Vogel|n|der|Vögel',
      'vier|x',
      'vorne|x',
      'vorbei|x',
      'verstehen|v|verstehst',
      'vergessen|v|vergisst',
      'verlieren|v|verlierst',
      'versuchen|v|versuchst',
      'Verein|n|der|Vereine',
      'Klavier|n|das|Klaviere',
      'Pullover|n|der|Pullover',
      'Vulkan|n|der|Vulkane',
      'Vase|n|die|Vasen',
      'Vanille|n|die|-',
    ],
  },
  {
    id: 'rs-x-chs-ks',
    name: 'x / chs / ks',
    emoji: '🦊',
    farbe: '#c2410c',
    gruppe: 'rechtschreibung',
    klasse: 4,
    woerter: [
      'Hexe|n|die|Hexen',
      'Text|n|der|Texte',
      'Taxi|n|das|Taxis',
      'Box|n|die|Boxen',
      'Axt|n|die|Äxte',
      'sechs|x',
      'Fuchs|n|der|Füchse',
      'wachsen|v|wächst',
      'Dachs|n|der|Dachse',
      'Ochse|n|der|Ochsen',
      'Wachs|n|das|-',
      'Büchse|n|die|Büchsen',
      'links|x',
      'Keks|n|der|Kekse',
      'Klecks|n|der|Kleckse',
    ],
  },
  {
    id: 'rs-qu-y-c',
    name: 'Qu / y / c',
    emoji: '🪼',
    farbe: '#38bdf8',
    gruppe: 'rechtschreibung',
    klasse: 4,
    woerter: [
      'Quelle|n|die|Quellen',
      'Qualle|n|die|Quallen',
      'quer|x',
      'Quatsch|n|der|-',
      'bequem|a|bequemer|am bequemsten',
      'Quark|n|der|-',
      'Quadrat|n|das|Quadrate',
      'Baby|n|das|Babys',
      'Hobby|n|das|Hobbys',
      'Handy|n|das|Handys',
      'Pony|n|das|Ponys',
      'Party|n|die|Partys',
      'Computer|n|der|Computer',
      'Clown|n|der|Clowns',
      'Alphabet|n|das|Alphabete',
    ],
  },
  {
    id: 'rs-langes-i',
    name: 'Langes i ohne ie',
    emoji: '🐯',
    farbe: '#f59e0b',
    gruppe: 'rechtschreibung',
    klasse: 4,
    woerter: [
      'Tiger|n|der|Tiger',
      'Kino|n|das|Kinos',
      'Igel|n|der|Igel',
      'Bibel|n|die|Bibeln',
      'Klima|n|das|-',
      'Liter|n|der|Liter',
      'Kiwi|n|die|Kiwis',
      'Pirat|n|der|Piraten',
      'Biber|n|der|Biber',
      'Maschine|n|die|Maschinen',
      'Benzin|n|das|-',
      'Kilo|n|das|Kilos',
      'Lilie|n|die|Lilien',
      'Linie|n|die|Linien',
      'Musik|n|die|-',
    ],
  },
  {
    id: 'rs-silben-h',
    name: 'Silbentrennendes h',
    emoji: '🌸',
    farbe: '#0284c7',
    gruppe: 'rechtschreibung',
    klasse: 4,
    // Wie beim Ableiten: Wo das h erst zwischen den Silben auftaucht, steht
    // die Grundform da (Schuh → die Schuhe, früh → früher).
    woerter: [
      'gehen|v|gehst',
      'stehen|v|stehst',
      'ziehen|v|ziehst',
      'sehen|v|siehst',
      'Ruhe|n|die|-',
      'Reihe|n|die|Reihen',
      'Schuh|n|der|Schuhe',
      'Kuh|n|die|Kühe',
      'blühen|v|blühst',
      'drohen|v|drohst',
      'Mühe|n|die|Mühen',
      'nähen|v|nähst',
      'Höhe|n|die|Höhen',
      'Nähe|n|die|-',
      'früh|a|früher|am frühesten',
    ],
  },
  {
    id: 'rs-vorsilben',
    name: 'Vorsilben',
    emoji: '🔎',
    farbe: '#ea580c',
    gruppe: 'rechtschreibung',
    klasse: 4,
    woerter: [
      'entdecken|v|entdeckst',
      'entschuldigen|v|entschuldigst',
      'Entschuldigung|n|die|Entschuldigungen',
      'entlang|x',
      'erklären|v|erklärst',
      'erzählen|v|erzählst',
      'erlauben|v|erlaubst',
      'bekommen|v|bekommst',
      'besuchen|v|besuchst',
      'bezahlen|v|bezahlst',
      'gewinnen|v|gewinnst',
      'gefallen|v|gefällst',
      'gehören|v|gehörst',
      'zerbrechen|v|zerbrichst',
      'zerreißen|v|zerreißt',
    ],
  },
  {
    id: 'rs-nachsilben-adj',
    name: '-ig / -lich / -isch',
    emoji: '🌈',
    farbe: '#eab308',
    gruppe: 'rechtschreibung',
    klasse: 4,
    woerter: [
      'lustig|a|lustiger|am lustigsten',
      'traurig|a|trauriger|am traurigsten',
      'richtig|a|richtiger|am richtigsten',
      'wichtig|a|wichtiger|am wichtigsten',
      'mutig|a|mutiger|am mutigsten',
      'fertig|a||',
      'freundlich|a|freundlicher|am freundlichsten',
      'gefährlich|a|gefährlicher|am gefährlichsten',
      'ehrlich|a|ehrlicher|am ehrlichsten',
      'glücklich|a|glücklicher|am glücklichsten',
      'fröhlich|a|fröhlicher|am fröhlichsten',
      'ängstlich|a|ängstlicher|am ängstlichsten',
      'komisch|a|komischer|am komischsten',
      'praktisch|a|praktischer|am praktischsten',
      'kindisch|a|kindischer|am kindischsten',
    ],
  },
  {
    id: 'rs-nachsilben-nomen',
    name: 'Nomen-Nachsilben',
    emoji: '🏅',
    farbe: '#2563eb',
    gruppe: 'rechtschreibung',
    klasse: 4,
    woerter: [
      'Zeugnis|n|das|Zeugnisse',
      'Ergebnis|n|das|Ergebnisse',
      'Erlebnis|n|das|Erlebnisse',
      'Geheimnis|n|das|Geheimnisse',
      'Hoffnung|n|die|Hoffnungen',
      'Übung|n|die|Übungen',
      'Meinung|n|die|Meinungen',
      'Freiheit|n|die|Freiheiten',
      'Wahrheit|n|die|Wahrheiten',
      'Gesundheit|n|die|-',
      'Schönheit|n|die|Schönheiten',
      'Freundlichkeit|n|die|-',
      'Möglichkeit|n|die|Möglichkeiten',
      'Freundschaft|n|die|Freundschaften',
      'Wissenschaft|n|die|Wissenschaften',
    ],
  },
  {
    id: 'rs-grossschreibung',
    name: 'Großschreibung',
    emoji: '🔤',
    farbe: '#0369a1',
    gruppe: 'rechtschreibung',
    klasse: 4,
    // Wortgruppen sind „keines davon". Worum es hier geht — die Großschreibung
    // — prüfen die Stufen 1, 2, 3 und 5 ohnehin buchstabengenau.
    woerter: [
      'Lesen|n|das|-',
      'Schwimmen|n|das|-',
      'Laufen|n|das|-',
      'Lachen|n|das|-',
      'beim Essen|x',
      'zum Spielen|x',
      'nach dem Schreiben|x',
      'das Beste|x',
      'etwas Schönes|x',
      'nichts Neues|x',
      'alles Gute|x',
      'die Kleinen|x',
      'die Großen|x',
      'im Dunkeln|x',
      'ins Freie|x',
    ],
  },
  {
    id: 'rs-stolpersteine',
    name: 'Stolpersteine · das / dass',
    emoji: '🪨',
    farbe: '#dc2626',
    gruppe: 'rechtschreibung',
    klasse: 4,
    woerter: [
      'das|x',
      'dass|x',
      'seit|x',
      'seid|x',
      'Stadt|n|die|Städte',
      'statt|x',
      'Meer|n|das|Meere',
      'mehr|x',
      'viel|x',
      'fiel|x',
      'war|x',
      'wahr|a||',
      'man|x',
      'Mann|n|der|Männer',
      'wieder|x',
    ],
  },
  {
    id: 'rs-fehlerwoerter-1',
    name: 'Häufige Fehlerwörter I',
    emoji: '👻',
    farbe: '#f97316',
    gruppe: 'rechtschreibung',
    klasse: 4,
    woerter: [
      'vielleicht|x',
      'plötzlich|a||',
      'nämlich|x',
      'ziemlich|x',
      'wahrscheinlich|a|wahrscheinlicher|am wahrscheinlichsten',
      'eigentlich|x',
      'endlich|x',
      'zusammen|x',
      'Geschichte|n|die|Geschichten',
      'Gespenst|n|das|Gespenster',
      'Familie|n|die|Familien',
      'Fenster|n|das|Fenster',
      'Schwester|n|die|Schwestern',
      'Geburtstag|n|der|Geburtstage',
      'Hausaufgabe|n|die|Hausaufgaben',
    ],
  },
  {
    id: 'rs-fehlerwoerter-2',
    name: 'Häufige Fehlerwörter II',
    emoji: '🥕',
    farbe: '#eab308',
    gruppe: 'rechtschreibung',
    klasse: 4,
    woerter: [
      'Herbst|n|der|Herbste',
      'Obst|n|das|-',
      'Arzt|n|der|Ärzte',
      'Gemüse|n|das|-',
      'Kartoffel|n|die|Kartoffeln',
      'Schokolade|n|die|Schokoladen',
      'Kaninchen|n|das|Kaninchen',
      'Pferd|n|das|Pferde',
      'Frühstück|n|das|Frühstücke',
      'Spinne|n|die|Spinnen',
      'Kürbis|n|der|Kürbisse',
      'Käfer|n|der|Käfer',
      'Zwiebel|n|die|Zwiebeln',
      'Zitrone|n|die|Zitronen',
      'Schnecke|n|die|Schnecken',
    ],
  },
  {
    id: 'rs-wochentage',
    name: 'Wochentage & Zeit',
    emoji: '📅',
    farbe: '#0ea5e9',
    gruppe: 'rechtschreibung',
    klasse: 4,
    woerter: [
      'Montag|n|der|Montage',
      'Dienstag|n|der|Dienstage',
      'Mittwoch|n|der|Mittwoche',
      'Donnerstag|n|der|Donnerstage',
      'Freitag|n|der|Freitage',
      'Samstag|n|der|Samstage',
      'Sonntag|n|der|Sonntage',
      'gestern|x',
      'heute|x',
      'morgen|x',
      'abends|x',
      'mittags|x',
      'Wochenende|n|das|Wochenenden',
      'Ferien|n|die|Ferien',
      'Minute|n|die|Minuten',
    ],
  },
  {
    id: 'rs-monate',
    name: 'Monate & Feste',
    emoji: '🎄',
    farbe: '#dc2626',
    gruppe: 'rechtschreibung',
    klasse: 4,
    woerter: [
      'Januar|n|der|-',
      'Februar|n|der|-',
      'März|n|der|-',
      'April|n|der|-',
      'Mai|n|der|-',
      'Juni|n|der|-',
      'Juli|n|der|-',
      'August|n|der|-',
      'September|n|der|-',
      'Oktober|n|der|-',
      'November|n|der|-',
      'Dezember|n|der|-',
      'Frühling|n|der|Frühlinge',
      'Winter|n|der|Winter',
      'Weihnachten|n|das|-',
    ],
  },
  {
    id: 'rs-zahlwoerter',
    name: 'Zahlwörter',
    emoji: '🔢',
    farbe: '#1d4ed8',
    gruppe: 'rechtschreibung',
    klasse: 4,
    // Zahlwörter sind in der Grundschulgrammatik weder Nomen noch Verb noch
    // Adjektiv. Stufe 4 hat in diesem Block also immer dieselbe Antwort —
    // und genau das ist die Lektion.
    woerter: [
      'elf|x',
      'zwölf|x',
      'dreizehn|x',
      'sechzehn|x',
      'zwanzig|x',
      'dreißig|x',
      'vierzig|x',
      'sechzig|x',
      'siebzig|x',
      'hundert|x',
      'tausend|x',
      'erste|x',
      'zweite|x',
      'dritte|x',
      'halb|x',
    ],
  },
];
