// Die mitgelieferten Themenbereiche der Wörterwerkstatt.
//
// Zwanzig Bereiche aus dem Grundschulalltag, je dreißig Lernwörter — das sind
// genau zwei Trainingspäckchen zu fünfzehn Wörtern je Bereich.
//
// Ausgewählt sind nicht irgendwelche Wörter, sondern solche, an denen die
// typischen Rechtschreibstellen der Grundschule hängen: Doppelkonsonant
// (Sonne, Teller), ie (Spiegel, Ziege), Dehnungs-h (Zahn, Ohr), ck und tz
// (Zucker, Katze), äu/eu (Bäume, Freund), tz/z, v/f (Vogel, Vater) und die
// Umlautbildung in der Mehrzahl (Baum → Bäume).
//
// Format je Wort — ein Textstück mit senkrechten Strichen, damit die Daten
// lesbar bleiben und die Datei klein:
//
//   Nomen      Ranzen|n|der|Ranzen           Wort | n | Artikel | Mehrzahl
//   Verb       laufen|v|läufst               Wort | v | 2. Person Einzahl
//   Adjektiv   schnell|a|schneller|am schnellsten
//   Sonstiges  heute|x                       Wort | x  (weder noch)
//
// Ein „-“ als Mehrzahl heißt: Dieses Nomen hat keine gebräuchliche Mehrzahl
// (Obst, Musik). Die Übung fragt dann nicht danach — Kinder sollen keine
// Formen erfinden müssen, die es nicht gibt.
//
// Zerlegt werden die Zeilen in grammatik.js; hier steht nur der Stoff.

export const BEREICHE = [
  {
    id: 'schule',
    name: 'Schule und Klasse',
    emoji: '🎒',
    farbe: '#2563eb',
    woerter: [
      'Ranzen|n|der|Ranzen',
      'Tafel|n|die|Tafeln',
      'Kreide|n|die|Kreiden',
      'Federmappe|n|die|Federmappen',
      'Schere|n|die|Scheren',
      'Lineal|n|das|Lineale',
      'Radiergummi|n|der|Radiergummis',
      'Bleistift|n|der|Bleistifte',
      'Heft|n|das|Hefte',
      'Buch|n|das|Bücher',
      'Pause|n|die|Pausen',
      'Klasse|n|die|Klassen',
      'Lehrerin|n|die|Lehrerinnen',
      'Zeugnis|n|das|Zeugnisse',
      'Aufgabe|n|die|Aufgaben',
      'Stundenplan|n|der|Stundenpläne',
      'Turnhalle|n|die|Turnhallen',
      'Pausenhof|n|der|Pausenhöfe',
      'Wörterbuch|n|das|Wörterbücher',
      'Diktat|n|das|Diktate',
      'lernen|v|lernst',
      'schreiben|v|schreibst',
      'lesen|v|liest',
      'rechnen|v|rechnest',
      'erklären|v|erklärst',
      'aufpassen|v|passt auf',
      'fleißig|a|fleißiger|am fleißigsten',
      'ruhig|a|ruhiger|am ruhigsten',
      'schwierig|a|schwieriger|am schwierigsten',
      'gestern|x',
    ],
  },
  {
    id: 'familie',
    name: 'Familie und Zuhause',
    emoji: '🏡',
    farbe: '#f97316',
    woerter: [
      'Familie|n|die|Familien',
      'Mutter|n|die|Mütter',
      'Vater|n|der|Väter',
      'Schwester|n|die|Schwestern',
      'Bruder|n|der|Brüder',
      'Großmutter|n|die|Großmütter',
      'Onkel|n|der|Onkel',
      'Tante|n|die|Tanten',
      'Wohnung|n|die|Wohnungen',
      'Küche|n|die|Küchen',
      'Zimmer|n|das|Zimmer',
      'Fenster|n|das|Fenster',
      'Treppe|n|die|Treppen',
      'Keller|n|der|Keller',
      'Teppich|n|der|Teppiche',
      'Sessel|n|der|Sessel',
      'Schrank|n|der|Schränke',
      'Garten|n|der|Gärten',
      'Bett|n|das|Betten',
      'Tür|n|die|Türen',
      'wohnen|v|wohnst',
      'putzen|v|putzt',
      'aufräumen|v|räumst auf',
      'helfen|v|hilfst',
      'schlafen|v|schläfst',
      'streiten|v|streitest',
      'gemütlich|a|gemütlicher|am gemütlichsten',
      'sauber|a|sauberer|am saubersten',
      'eng|a|enger|am engsten',
      'zusammen|x',
    ],
  },
  {
    id: 'haustiere',
    name: 'Haustiere und Bauernhof',
    emoji: '🐄',
    farbe: '#eab308',
    woerter: [
      'Katze|n|die|Katzen',
      'Hund|n|der|Hunde',
      'Kaninchen|n|das|Kaninchen',
      'Hamster|n|der|Hamster',
      'Pferd|n|das|Pferde',
      'Kuh|n|die|Kühe',
      'Schwein|n|das|Schweine',
      'Ziege|n|die|Ziegen',
      'Schaf|n|das|Schafe',
      'Huhn|n|das|Hühner',
      'Ente|n|die|Enten',
      'Gans|n|die|Gänse',
      'Stall|n|der|Ställe',
      'Scheune|n|die|Scheunen',
      'Traktor|n|der|Traktoren',
      'Futter|n|das|-',
      'Weide|n|die|Weiden',
      'Bauernhof|n|der|Bauernhöfe',
      'Käfig|n|der|Käfige',
      'Fell|n|das|Felle',
      'füttern|v|fütterst',
      'streicheln|v|streichelst',
      'bellen|v|bellst',
      'reiten|v|reitest',
      'melken|v|melkst',
      'wiehern|v|wieherst',
      'zahm|a|zahmer|am zahmsten',
      'flauschig|a|flauschiger|am flauschigsten',
      'neugierig|a|neugieriger|am neugierigsten',
      'draußen|x',
    ],
  },
  {
    id: 'wildtiere',
    name: 'Wilde Tiere und Zoo',
    emoji: '🦁',
    farbe: '#ea580c',
    woerter: [
      'Löwe|n|der|Löwen',
      'Elefant|n|der|Elefanten',
      'Giraffe|n|die|Giraffen',
      'Affe|n|der|Affen',
      'Bär|n|der|Bären',
      'Wolf|n|der|Wölfe',
      'Fuchs|n|der|Füchse',
      'Igel|n|der|Igel',
      'Eichhörnchen|n|das|Eichhörnchen',
      'Schlange|n|die|Schlangen',
      'Krokodil|n|das|Krokodile',
      'Pinguin|n|der|Pinguine',
      'Adler|n|der|Adler',
      'Zebra|n|das|Zebras',
      'Tiger|n|der|Tiger',
      'Gehege|n|das|Gehege',
      'Rüssel|n|der|Rüssel',
      'Tatze|n|die|Tatzen',
      'Schnabel|n|der|Schnäbel',
      'Wildnis|n|die|-',
      'brüllen|v|brüllst',
      'jagen|v|jagst',
      'klettern|v|kletterst',
      'fressen|v|frisst',
      'schleichen|v|schleichst',
      'beobachten|v|beobachtest',
      'gefährlich|a|gefährlicher|am gefährlichsten',
      'wild|a|wilder|am wildesten',
      'riesig|a|riesiger|am riesigsten',
      'überall|x',
    ],
  },
  {
    id: 'wald',
    name: 'Wald und Bäume',
    emoji: '🌲',
    farbe: '#0284c7',
    woerter: [
      'Wald|n|der|Wälder',
      'Baum|n|der|Bäume',
      'Blatt|n|das|Blätter',
      'Ast|n|der|Äste',
      'Wurzel|n|die|Wurzeln',
      'Stamm|n|der|Stämme',
      'Rinde|n|die|Rinden',
      'Tanne|n|die|Tannen',
      'Eiche|n|die|Eichen',
      'Birke|n|die|Birken',
      'Pilz|n|der|Pilze',
      'Moos|n|das|Moose',
      'Beere|n|die|Beeren',
      'Zapfen|n|der|Zapfen',
      'Lichtung|n|die|Lichtungen',
      'Förster|n|der|Förster',
      'Nest|n|das|Nester',
      'Waldweg|n|der|Waldwege',
      'Schatten|n|der|Schatten',
      'Käfer|n|der|Käfer',
      'wachsen|v|wächst',
      'sammeln|v|sammelst',
      'rascheln|v|raschelst',
      'wandern|v|wanderst',
      'pflanzen|v|pflanzt',
      'suchen|v|suchst',
      'dicht|a|dichter|am dichtesten',
      'still|a|stiller|am stillsten',
      'hoch|a|höher|am höchsten',
      'mitten|x',
    ],
  },
  {
    id: 'wetter',
    name: 'Wetter und Jahreszeiten',
    emoji: '🌦️',
    farbe: '#38bdf8',
    woerter: [
      'Sonne|n|die|Sonnen',
      'Regen|n|der|-',
      'Wolke|n|die|Wolken',
      'Schnee|n|der|-',
      'Wind|n|der|Winde',
      'Gewitter|n|das|Gewitter',
      'Blitz|n|der|Blitze',
      'Donner|n|der|-',
      'Nebel|n|der|Nebel',
      'Frühling|n|der|Frühlinge',
      'Sommer|n|der|Sommer',
      'Herbst|n|der|Herbste',
      'Winter|n|der|Winter',
      'Regenbogen|n|der|Regenbögen',
      'Pfütze|n|die|Pfützen',
      'Schneeflocke|n|die|Schneeflocken',
      'Hitze|n|die|-',
      'Kälte|n|die|-',
      'Jahreszeit|n|die|Jahreszeiten',
      'Schirm|n|der|Schirme',
      'regnen|v|regnest',
      'schneien|v|schneist',
      'frieren|v|frierst',
      'scheinen|v|scheinst',
      'stürmen|v|stürmst',
      'tauen|v|taust',
      'warm|a|wärmer|am wärmsten',
      'kalt|a|kälter|am kältesten',
      'nass|a|nasser|am nassesten',
      'heute|x',
    ],
  },
  {
    id: 'essen',
    name: 'Essen und Trinken',
    emoji: '🍎',
    farbe: '#dc2626',
    woerter: [
      'Apfel|n|der|Äpfel',
      'Birne|n|die|Birnen',
      'Banane|n|die|Bananen',
      'Kartoffel|n|die|Kartoffeln',
      'Tomate|n|die|Tomaten',
      'Gurke|n|die|Gurken',
      'Möhre|n|die|Möhren',
      'Brot|n|das|Brote',
      'Brötchen|n|das|Brötchen',
      'Butter|n|die|-',
      'Käse|n|der|Käse',
      'Wurst|n|die|Würste',
      'Suppe|n|die|Suppen',
      'Nudel|n|die|Nudeln',
      'Zucker|n|der|-',
      'Salz|n|das|-',
      'Milch|n|die|-',
      'Saft|n|der|Säfte',
      'Kuchen|n|der|Kuchen',
      'Obst|n|das|-',
      'essen|v|isst',
      'trinken|v|trinkst',
      'kochen|v|kochst',
      'backen|v|bäckst',
      'schmecken|v|schmeckst',
      'schneiden|v|schneidest',
      'lecker|a|leckerer|am leckersten',
      'süß|a|süßer|am süßesten',
      'sauer|a|saurer|am sauersten',
      'genug|x',
    ],
  },
  {
    id: 'kleidung',
    name: 'Kleidung',
    emoji: '🧥',
    farbe: '#1d4ed8',
    woerter: [
      'Hose|n|die|Hosen',
      'Jacke|n|die|Jacken',
      'Pullover|n|der|Pullover',
      'Hemd|n|das|Hemden',
      'Kleid|n|das|Kleider',
      'Rock|n|der|Röcke',
      'Mantel|n|der|Mäntel',
      'Mütze|n|die|Mützen',
      'Schal|n|der|Schals',
      'Handschuh|n|der|Handschuhe',
      'Strumpf|n|der|Strümpfe',
      'Schuh|n|der|Schuhe',
      'Stiefel|n|der|Stiefel',
      'Gürtel|n|der|Gürtel',
      'Knopf|n|der|Knöpfe',
      'Tasche|n|die|Taschen',
      'Kapuze|n|die|Kapuzen',
      'Reißverschluss|n|der|Reißverschlüsse',
      'Stoff|n|der|Stoffe',
      'Anzug|n|der|Anzüge',
      'anziehen|v|ziehst an',
      'ausziehen|v|ziehst aus',
      'tragen|v|trägst',
      'nähen|v|nähst',
      'waschen|v|wäschst',
      'passen|v|passt',
      'warm|a|wärmer|am wärmsten',
      'bunt|a|bunter|am buntesten',
      'weich|a|weicher|am weichsten',
      'darüber|x',
    ],
  },
  {
    id: 'koerper',
    name: 'Körper und Gesundheit',
    emoji: '🩺',
    farbe: '#dc2626',
    woerter: [
      'Kopf|n|der|Köpfe',
      'Auge|n|das|Augen',
      'Ohr|n|das|Ohren',
      'Nase|n|die|Nasen',
      'Mund|n|der|Münder',
      'Zahn|n|der|Zähne',
      'Hand|n|die|Hände',
      'Finger|n|der|Finger',
      'Arm|n|der|Arme',
      'Bein|n|das|Beine',
      'Fuß|n|der|Füße',
      'Rücken|n|der|Rücken',
      'Bauch|n|der|Bäuche',
      'Herz|n|das|Herzen',
      'Knochen|n|der|Knochen',
      'Haar|n|das|Haare',
      'Arzt|n|der|Ärzte',
      'Pflaster|n|das|Pflaster',
      'Fieber|n|das|-',
      'Husten|n|der|-',
      'atmen|v|atmest',
      'niesen|v|niest',
      'wachsen|v|wächst',
      'fühlen|v|fühlst',
      'heilen|v|heilst',
      'schwitzen|v|schwitzt',
      'gesund|a|gesünder|am gesündesten',
      'krank|a|kränker|am kränksten',
      'müde|a|müder|am müdesten',
      'schon|x',
    ],
  },
  {
    id: 'sport',
    name: 'Sport und Bewegung',
    emoji: '⚽',
    farbe: '#0ea5e9',
    woerter: [
      'Sport|n|der|-',
      'Ball|n|der|Bälle',
      'Tor|n|das|Tore',
      'Mannschaft|n|die|Mannschaften',
      'Turnschuh|n|der|Turnschuhe',
      'Matte|n|die|Matten',
      'Seil|n|das|Seile',
      'Barren|n|der|Barren',
      'Wettkampf|n|der|Wettkämpfe',
      'Sieger|n|der|Sieger',
      'Pokal|n|der|Pokale',
      'Trainer|n|der|Trainer',
      'Übung|n|die|Übungen',
      'Sprung|n|der|Sprünge',
      'Rolle|n|die|Rollen',
      'Schwimmbad|n|das|Schwimmbäder',
      'Fahrrad|n|das|Fahrräder',
      'Regel|n|die|Regeln',
      'Pfiff|n|der|Pfiffe',
      'Punkt|n|der|Punkte',
      'laufen|v|läufst',
      'springen|v|springst',
      'werfen|v|wirfst',
      'fangen|v|fängst',
      'schwimmen|v|schwimmst',
      'gewinnen|v|gewinnst',
      'stark|a|stärker|am stärksten',
      'schnell|a|schneller|am schnellsten',
      'fair|a|fairer|am fairsten',
      'immer|x',
    ],
  },
  {
    id: 'verkehr',
    name: 'Verkehr und unterwegs',
    emoji: '🚌',
    farbe: '#0369a1',
    woerter: [
      'Straße|n|die|Straßen',
      'Ampel|n|die|Ampeln',
      'Zebrastreifen|n|der|Zebrastreifen',
      'Gehweg|n|der|Gehwege',
      'Auto|n|das|Autos',
      'Bus|n|der|Busse',
      'Zug|n|der|Züge',
      'Bahnhof|n|der|Bahnhöfe',
      'Haltestelle|n|die|Haltestellen',
      'Fahrkarte|n|die|Fahrkarten',
      'Roller|n|der|Roller',
      'Helm|n|der|Helme',
      'Kreuzung|n|die|Kreuzungen',
      'Schild|n|das|Schilder',
      'Brücke|n|die|Brücken',
      'Tunnel|n|der|Tunnel',
      'Reifen|n|der|Reifen',
      'Lastwagen|n|der|Lastwagen',
      'Fahrer|n|der|Fahrer',
      'Weg|n|der|Wege',
      'fahren|v|fährst',
      'bremsen|v|bremst',
      'warten|v|wartest',
      'einsteigen|v|steigst ein',
      'überqueren|v|überquerst',
      'anhalten|v|hältst an',
      'vorsichtig|a|vorsichtiger|am vorsichtigsten',
      'weit|a|weiter|am weitesten',
      'gefährlich|a|gefährlicher|am gefährlichsten',
      'rechts|x',
    ],
  },
  {
    id: 'stadt',
    name: 'Stadt und Einkaufen',
    emoji: '🏬',
    farbe: '#f59e0b',
    woerter: [
      'Stadt|n|die|Städte',
      'Markt|n|der|Märkte',
      'Geschäft|n|das|Geschäfte',
      'Bäckerei|n|die|Bäckereien',
      'Metzgerei|n|die|Metzgereien',
      'Apotheke|n|die|Apotheken',
      'Kasse|n|die|Kassen',
      'Geld|n|das|-',
      'Münze|n|die|Münzen',
      'Preis|n|der|Preise',
      'Kunde|n|der|Kunden',
      'Korb|n|der|Körbe',
      'Regal|n|das|Regale',
      'Rathaus|n|das|Rathäuser',
      'Kirche|n|die|Kirchen',
      'Bücherei|n|die|Büchereien',
      'Spielplatz|n|der|Spielplätze',
      'Schaufenster|n|das|Schaufenster',
      'Quittung|n|die|Quittungen',
      'Tüte|n|die|Tüten',
      'kaufen|v|kaufst',
      'bezahlen|v|bezahlst',
      'verkaufen|v|verkaufst',
      'bringen|v|bringst',
      'wiegen|v|wiegst',
      'aussuchen|v|suchst aus',
      'teuer|a|teurer|am teuersten',
      'billig|a|billiger|am billigsten',
      'voll|a|voller|am vollsten',
      'endlich|x',
    ],
  },
  {
    id: 'farbenformen',
    name: 'Farben und Formen',
    emoji: '🎨',
    farbe: '#facc15',
    woerter: [
      'Farbe|n|die|Farben',
      'Kreis|n|der|Kreise',
      'Quadrat|n|das|Quadrate',
      'Dreieck|n|das|Dreiecke',
      'Rechteck|n|das|Rechtecke',
      'Würfel|n|der|Würfel',
      'Kugel|n|die|Kugeln',
      'Linie|n|die|Linien',
      'Ecke|n|die|Ecken',
      'Kante|n|die|Kanten',
      'Muster|n|das|Muster',
      'Pinsel|n|der|Pinsel',
      'Stift|n|der|Stifte',
      'Papier|n|das|Papiere',
      'Bild|n|das|Bilder',
      'Streifen|n|der|Streifen',
      'Punkt|n|der|Punkte',
      'Schere|n|die|Scheren',
      'Kleber|n|der|Kleber',
      'Pinnwand|n|die|Pinnwände',
      'malen|v|malst',
      'zeichnen|v|zeichnest',
      'kleben|v|klebst',
      'falten|v|faltest',
      'mischen|v|mischst',
      'ausschneiden|v|schneidest aus',
      'rund|a|runder|am rundesten',
      'eckig|a|eckiger|am eckigsten',
      'hell|a|heller|am hellsten',
      'daneben|x',
    ],
  },
  {
    id: 'zahlen',
    name: 'Zahlen und Rechnen',
    emoji: '🔢',
    farbe: '#2563eb',
    woerter: [
      'Zahl|n|die|Zahlen',
      'Ziffer|n|die|Ziffern',
      'Summe|n|die|Summen',
      'Hälfte|n|die|Hälften',
      'Rest|n|der|Reste',
      'Zwilling|n|der|Zwillinge',
      'Dutzend|n|das|Dutzende',
      'Meter|n|der|Meter',
      'Zentimeter|n|der|Zentimeter',
      'Kilogramm|n|das|Kilogramm',
      'Liter|n|der|Liter',
      'Stunde|n|die|Stunden',
      'Minute|n|die|Minuten',
      'Uhrzeit|n|die|Uhrzeiten',
      'Waage|n|die|Waagen',
      'Tabelle|n|die|Tabellen',
      'Ergebnis|n|das|Ergebnisse',
      'Reihe|n|die|Reihen',
      'Rechnung|n|die|Rechnungen',
      'Zirkel|n|der|Zirkel',
      'zählen|v|zählst',
      'addieren|v|addierst',
      'teilen|v|teilst',
      'messen|v|misst',
      'schätzen|v|schätzt',
      'vergleichen|v|vergleichst',
      'schwer|a|schwerer|am schwersten',
      'genau|a|genauer|am genauesten',
      'wenig|a|weniger|am wenigsten',
      'zuerst|x',
    ],
  },
  {
    id: 'gefuehle',
    name: 'Gefühle und Miteinander',
    emoji: '💛',
    farbe: '#fbbf24',
    woerter: [
      'Freund|n|der|Freunde',
      'Freundin|n|die|Freundinnen',
      'Gefühl|n|das|Gefühle',
      'Freude|n|die|Freuden',
      'Angst|n|die|Ängste',
      'Wut|n|die|-',
      'Trauer|n|die|-',
      'Streit|n|der|Streite',
      'Entschuldigung|n|die|Entschuldigungen',
      'Vertrauen|n|das|-',
      'Geheimnis|n|das|Geheimnisse',
      'Rücksicht|n|die|-',
      'Hilfe|n|die|-',
      'Mut|n|der|-',
      'Träne|n|die|Tränen',
      'Lächeln|n|das|-',
      'Wunsch|n|der|Wünsche',
      'Ärger|n|der|-',
      'Sorge|n|die|Sorgen',
      'Versprechen|n|das|Versprechen',
      'lachen|v|lachst',
      'weinen|v|weinst',
      'trösten|v|tröstest',
      'ärgern|v|ärgerst',
      'vertragen|v|verträgst',
      'zuhören|v|hörst zu',
      'traurig|a|trauriger|am traurigsten',
      'fröhlich|a|fröhlicher|am fröhlichsten',
      'wütend|a|wütender|am wütendsten',
      'vielleicht|x',
    ],
  },
  {
    id: 'spielen',
    name: 'Spielen und Freizeit',
    emoji: '🪁',
    farbe: '#38bdf8',
    woerter: [
      'Spiel|n|das|Spiele',
      'Puppe|n|die|Puppen',
      'Puzzle|n|das|Puzzles',
      'Schaukel|n|die|Schaukeln',
      'Rutsche|n|die|Rutschen',
      'Sandkasten|n|der|Sandkästen',
      'Drachen|n|der|Drachen',
      'Murmel|n|die|Murmeln',
      'Versteck|n|das|Verstecke',
      'Würfel|n|der|Würfel',
      'Karte|n|die|Karten',
      'Zelt|n|das|Zelte',
      'Ferien|n|die|Ferien',
      'Ausflug|n|der|Ausflüge',
      'Geburtstag|n|der|Geburtstage',
      'Geschenk|n|das|Geschenke',
      'Kino|n|das|Kinos',
      'Zirkus|n|der|Zirkusse',
      'Baumhaus|n|das|Baumhäuser',
      'Schatz|n|der|Schätze',
      'spielen|v|spielst',
      'schaukeln|v|schaukelst',
      'verstecken|v|versteckst',
      'basteln|v|bastelst',
      'gewinnen|v|gewinnst',
      'einladen|v|lädst ein',
      'lustig|a|lustiger|am lustigsten',
      'spannend|a|spannender|am spannendsten',
      'langweilig|a|langweiliger|am langweiligsten',
      'draußen|x',
    ],
  },
  {
    id: 'musik',
    name: 'Musik und Instrumente',
    emoji: '🎺',
    farbe: '#c2410c',
    woerter: [
      'Musik|n|die|-',
      'Lied|n|das|Lieder',
      'Note|n|die|Noten',
      'Takt|n|der|Takte',
      'Flöte|n|die|Flöten',
      'Trommel|n|die|Trommeln',
      'Gitarre|n|die|Gitarren',
      'Klavier|n|das|Klaviere',
      'Geige|n|die|Geigen',
      'Trompete|n|die|Trompeten',
      'Glocke|n|die|Glocken',
      'Chor|n|der|Chöre',
      'Stimme|n|die|Stimmen',
      'Bühne|n|die|Bühnen',
      'Konzert|n|das|Konzerte',
      'Klang|n|der|Klänge',
      'Rhythmus|n|der|Rhythmen',
      'Pause|n|die|Pausen',
      'Saite|n|die|Saiten',
      'Publikum|n|das|-',
      'singen|v|singst',
      'spielen|v|spielst',
      'klingen|v|klingst',
      'üben|v|übst',
      'klatschen|v|klatschst',
      'zuhören|v|hörst zu',
      'laut|a|lauter|am lautesten',
      'leise|a|leiser|am leisesten',
      'schön|a|schöner|am schönsten',
      'niemals|x',
    ],
  },
  {
    id: 'wasser',
    name: 'Wasser und Meer',
    emoji: '🌊',
    farbe: '#0284c7',
    woerter: [
      'Wasser|n|das|-',
      'Meer|n|das|Meere',
      'Welle|n|die|Wellen',
      'Strand|n|der|Strände',
      'Muschel|n|die|Muscheln',
      'Sand|n|der|-',
      'Insel|n|die|Inseln',
      'Schiff|n|das|Schiffe',
      'Boot|n|das|Boote',
      'Segel|n|das|Segel',
      'Anker|n|der|Anker',
      'Hafen|n|der|Häfen',
      'Fisch|n|der|Fische',
      'Möwe|n|die|Möwen',
      'Qualle|n|die|Quallen',
      'Krebs|n|der|Krebse',
      'Fluss|n|der|Flüsse',
      'Bach|n|der|Bäche',
      'Brunnen|n|der|Brunnen',
      'Ufer|n|das|Ufer',
      'schwimmen|v|schwimmst',
      'tauchen|v|tauchst',
      'segeln|v|segelst',
      'angeln|v|angelst',
      'spritzen|v|spritzt',
      'fließen|v|fließt',
      'tief|a|tiefer|am tiefsten',
      'salzig|a|salziger|am salzigsten',
      'glatt|a|glatter|am glattesten',
      'unten|x',
    ],
  },
  {
    id: 'weltraum',
    name: 'Weltraum und Himmel',
    emoji: '🚀',
    farbe: '#1e40af',
    woerter: [
      'Himmel|n|der|Himmel',
      'Stern|n|der|Sterne',
      'Mond|n|der|Monde',
      'Planet|n|der|Planeten',
      'Erde|n|die|-',
      'Rakete|n|die|Raketen',
      'Weltall|n|das|-',
      'Komet|n|der|Kometen',
      'Teleskop|n|das|Teleskope',
      'Umlaufbahn|n|die|Umlaufbahnen',
      'Schwerkraft|n|die|-',
      'Sternbild|n|das|Sternbilder',
      'Astronaut|n|der|Astronauten',
      'Sauerstoff|n|der|-',
      'Krater|n|der|Krater',
      'Galaxie|n|die|Galaxien',
      'Sonnensystem|n|das|Sonnensysteme',
      'Raumschiff|n|das|Raumschiffe',
      'Finsternis|n|die|Finsternisse',
      'Meteorit|n|der|Meteoriten',
      'fliegen|v|fliegst',
      'starten|v|startest',
      'landen|v|landest',
      'leuchten|v|leuchtest',
      'kreisen|v|kreist',
      'erforschen|v|erforschst',
      'dunkel|a|dunkler|am dunkelsten',
      'weit|a|weiter|am weitesten',
      'hell|a|heller|am hellsten',
      'darüber|x',
    ],
  },
  {
    id: 'feste',
    name: 'Feste und Feiern',
    emoji: '🎉',
    farbe: '#eab308',
    woerter: [
      'Fest|n|das|Feste',
      'Geburtstag|n|der|Geburtstage',
      'Kerze|n|die|Kerzen',
      'Torte|n|die|Torten',
      'Luftballon|n|der|Luftballons',
      'Girlande|n|die|Girlanden',
      'Einladung|n|die|Einladungen',
      'Gast|n|der|Gäste',
      'Überraschung|n|die|Überraschungen',
      'Weihnachten|n|das|-',
      'Ostern|n|das|-',
      'Fasching|n|der|-',
      'Kostüm|n|das|Kostüme',
      'Maske|n|die|Masken',
      'Konfetti|n|das|-',
      'Umzug|n|der|Umzüge',
      'Laterne|n|die|Laternen',
      'Feuerwerk|n|das|Feuerwerke',
      'Wunschzettel|n|der|Wunschzettel',
      'Jahrmarkt|n|der|Jahrmärkte',
      'feiern|v|feierst',
      'schenken|v|schenkst',
      'einladen|v|lädst ein',
      'schmücken|v|schmückst',
      'tanzen|v|tanzt',
      'verkleiden|v|verkleidest',
      'festlich|a|festlicher|am festlichsten',
      'aufgeregt|a|aufgeregter|am aufgeregtesten',
      'geheim|a|geheimer|am geheimsten',
      'bald|x',
    ],
  },
];
